### PR TITLE
uniphier: clean-up platform makefile

### PR DESCRIPTION
**Pull request by masahir0y**

### CODE REVIEW

**Comment by davidcunado-arm** [comment]
jenkins: test this please

**Comment by masahir0y** [comment]
Seems the test failed.
Where can I see the detail of the test result?

**Comment by soby-mathew** [comment]
@masahir0y, seems to have been an internal CI issue. Unfortunately, the test results are not visible externally. I have re-triggered the test and it seems to be proceeding well now.

**Comment by davidcunado-arm** [comment]
jenkins: test this please

**Comment by davidcunado-arm** [comment]
jenkins: test this please

**Pull request merged**
