### PR TITLE
Fix MIDR_EL1 value for Neoverse E1

### PR DESCRIPTION
**Pull request by jts-arm**
Change-Id: I75ee39d78c81ecb528a671c0cfadfc2fe7b5d818
Signed-off-by: John Tsichritzis <john.tsichritzis@arm.com>

### CODE REVIEW

**Comment by soby-mathew** [comment]
@omasab , Could you let us know how this affects n1sdp platforms ?

**Comment by thomas-arm** [comment]
@soby-mathew, I have not been able to access the test log to check the issue (it does not exist now). But this patch should not have affected n1sdp. Are you referring to rde1edge platform instead? Any links to access to test log to check the failures?

**Comment by soby-mathew** [comment]
jenkins: test this please

**Comment by soby-mathew** [comment]
@omasab, I think we will merge this PR eventhough the rde1edge models are not updated yet for the new MIDR value.

**Pull request merged**
