### PR TITLE
Tegra soc support v4

### PR DESCRIPTION
**Pull request by vwadekar**
T210 is the latest chip in the Tegra family of SoCs from NVIDIA. It is an
ARM v8 dual-cluster (A57/A53) SoC, with any one of the clusters being active
at a given point in time.

This patch adds support to boot the Trusted Firmware on T210 SoCs. The patch
also adds support to boot secondary CPUs, enter/exit core power states for
all CPUs in the slow/fast clusters. The support to switch between clusters
is still not available in this patch and would be available later.

### CODE REVIEW

**Comment by vwadekar** [comment]
Fixed style errors from #306

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by achingupta** [comment]
test this please

**Comment by vwadekar** [comment]
Achin, are you planning to merge this change today? Please let me know if I could help out in any way.

**Comment by achingupta** [comment]
Varun, We will be able to do this first thing tomorrow. Dan is on holiday today and I need a final signoff from him. Apologies for the delay and thanks for rolling in the feedback.

**Comment by vwadekar** [comment]
Thanks. Do let me know if anything else needs to be fixed.

**Comment by vwadekar** [comment]
Thanks  a lot Achin.

**Comment by achingupta** [comment]
Thanks for the quick reworks :) I will keep you updated on the progress of phase 1 of tf-issues/#304

**Comment by vwadekar** [comment]
Sure. When can I expect the merge from integration->master branch?

**Comment by achingupta** [comment]
Done now. Apologies for the delay.

**Comment by vwadekar** [comment]
Thanks again. Appreciate it.

**Pull request merged**
