### PR TITLE
Rm emmc delay

### PR DESCRIPTION
**Pull request by hzhuang1**

### CODE REVIEW

**Comment by antonio-nino-diaz-arm** [comment]
IP Review +1

**Comment by antonio-nino-diaz-arm** [comment]
CC: @bryanodonoghue, @shawnguo2 and @Yann-lms (though according to @ldebieve it is working).

**Comment by bryanodonoghue** [comment]
Tested-by: Bryan O'Donoghue <bryan.odonoghue@linaro.org>

**Comment by antonio-nino-diaz-arm** [comment]
jenkins: test this please

**Pull request merged**
