### PR TITLE
Create TOC links in the User Guide markdown file

### PR DESCRIPTION
**Pull request by jbech-linaro**
Fixes arm-software/tf-issues#276

### CODE REVIEW

**Comment by danh-arm** [comment]
Hi Joakim

This pull request just needs a few minor tweaks and then I'll merge.

Regards

Dan.

**Comment by jbech-linaro** [comment]
Hi Dan,

Sure, I will fix the nits, but I'll keep the long links since I haven't got a definite answer from you regarding those. Sounds good?

**Comment by jbech-linaro** [comment]
Updated patch has been pushed, please let me know if this is OK or if you need additional changes.

**Comment by danh-arm** [comment]
As a matter of interest, are you using a tool to automatically generate these ToCs? If so, can you point us to which one?

**Comment by jbech-linaro** [comment]
For this particular patch I did it manually, I.e, copy/pasted the URL you get when hovering the mouse pointer over the different sections. But I have also tried http://doctoc.herokuapp.com/ in the past which did half of the job (creating the TOC).

**Pull request merged**
