### PR TITLE
Big core suspend

### PR DESCRIPTION
**Pull request by mtk09422**
Previous review https://github.com/ARM-software/arm-trusted-firmware/pull/384

1. Add gpio interface to read gpio status
2. support big core buck/PLL control in system suspend flow

### CODE REVIEW

**Comment by achingupta** [comment]
test this please

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by danh-arm** [comment]
I'm expecting this PR to be reworked following the discusson on the Oak mailing list titled "New PR 391/392/393 for arm-trusted-firmware mt8173 platform code update"

**Pull request closed without merging**
