### PR TITLE
Tegra supports psci1.0 v2

### PR DESCRIPTION
**Pull request by vwadekar**
Tegra: support PSCI v1.0 framework implementation

This patch modifies the Tegra port to support the new PSCI v1.0
implementation. This includes modifications to the power management
and platform topology code.

Previous PR - #372

### CODE REVIEW

**Comment by vwadekar** [comment]
@soby-mathew 

Hello Soby,

Do let me know if you have any more comments.

Thanks.

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by vwadekar** [comment]
New PR - #379

**Pull request closed without merging**
