### PR TITLE
Mediatek bl31

### PR DESCRIPTION
**Pull request by mtk09422**
Add plat parameter structures and memory configuration for Mediatek BL31

previous PR: https://github.com/ARM-software/arm-trusted-firmware/pull/436

### CODE REVIEW

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by danh-arm** [comment]
test this please

**Comment by danh-arm** [comment]
This PR failed to build in release mode:
```
Build options: CROSS_COMPILE=aarch64-linux-gnu- V=1 PLAT=mt8173
```

```
plat/mediatek/mt8173/params_setup.c
aarch64-linux-gnu-gcc -nostdinc -ffreestanding -Wall -Werror -Wmissing-include-dirs -mgeneral-regs-only -mstrict-align -std=c99 -c -Os -DDEBUG=0 -DNDEBUG -DARM_GIC_ARCH=2 -DSKIP_A57_L1_FLUSH_PWR_DWN=0 -DERRATA_A53_826319=1 -DERRATA_A53_836870=1 -DERRATA_A57_806969=0 -DERRATA_A57_813420=0 -DPLAT_mt8173 -DNS_TIMER_SWITCH=0 -DRESET_TO_BL31=0 -DCTX_INCLUDE_FPREGS=0 -DARM_GIC_ARCH=2 -DARM_CCI_PRODUCT_ID=400 -DASM_ASSERTION=0 -DLOG_LEVEL=20 -DUSE_COHERENT_MEM=1 -DTRUSTED_BOARD_BOOT=0 -DPROGRAMMABLE_RESET_ADDRESS=1 -DCOLD_BOOT_SINGLE_CPU=0 -DPSCI_EXTENDED_STATE_ID=0 -DERROR_DEPRECATED=0 -DENABLE_PLAT_COMPAT=1 -DSPIN_ON_BL1_EXIT=0 -DCRASH_REPORTING=0 -Iinclude/bl31 -Iinclude/bl31/services -Iinclude/common -Iinclude/drivers -Iinclude/drivers/arm -Iinclude/drivers/auth -Iinclude/drivers/io -Iinclude/drivers/ti/uart -Iinclude/lib -Iinclude/lib/aarch64 -Iinclude/lib/cpus/aarch64 -Iinclude/plat/common -Iinclude/stdlib -Iinclude/stdlib/sys -Iplat/mediatek/common/ -Iplat/mediatek/mt8173/drivers/gpio/ -Iplat/mediatek/mt8173/drivers/i2c/ -Iplat/mediatek/mt8173/drivers/mtcmos/ -Iplat/mediatek/mt8173/drivers/pmic/ -Iplat/mediatek/mt8173/drivers/rtc/ -Iplat/mediatek/mt8173/drivers/spm/ -Iplat/mediatek/mt8173/drivers/timer/ -Iplat/mediatek/mt8173/drivers/uart/ -Iplat/mediatek/mt8173/include/  -ffunction-sections -fdata-sections -pedantic -Wno-error=deprecated-declarations -DIMAGE_BL31 -c plat/mediatek/mt8173/params_setup.c -o build/mt8173/release/bl31/params_setup.o
plat/mediatek/mt8173/params_setup.c: In function 'params_early_setup':
plat/mediatek/mt8173/params_setup.c:73:3: error: 'param' may be used uninitialized in this function [-Werror=maybe-uninitialized]
   memcpy((void *)param, (void *)bl2_param, size);
   ^
plat/mediatek/mt8173/params_setup.c:73:3: error: 'size' may be used uninitialized in this function [-Werror=maybe-uninitialized]
cc1: all warnings being treated as errors
make: *** [build/mt8173/release/bl31/params_setup.o] Error 1
Build failed with code 2
```

**Comment by jimmyh-mtk** [comment]
We fix the 'build error' and update the code in #447 directly (same PR). Could you trigger test build again?

**Comment by mtk09422** [comment]
Hardware will handle the buck control on latest mt8173 platform.

da9212 and mt6311 initialization code are no longer needed in ARM-TF.
We will also remove the board parameters passing related code from ARM-TF.

**Pull request closed without merging**
