### PR TITLE
Tegra modifications v1

### PR DESCRIPTION
**Pull request by vwadekar**
Miscellaneous patches for fixing minor bugs in the Tegra port and to  provide more control to the SoCs rather than the common code.

### CODE REVIEW

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by danh-arm** [comment]
test this please

**Comment by danh-arm** [comment]
retest this please

**Comment by danh-arm** [comment]
@vwadekar 

This PR seems to have stalled, Varun. You indicated that you were going to rework this (even though my comments were not gating). Are you still planning to rework? I guess a rebase at least would be good.

**Comment by vwadekar** [comment]
Yes. I will get this going. Was busy in other tasks and so did not get
time.

**Comment by vwadekar** [comment]
Closing for now. Will push a new PR if required.

**Pull request closed without merging**
