### PR TITLE
mmc: Update framework to use standard response type

### PR DESCRIPTION
**Pull request by Yann-lms**
Respect official response type and update response to follow
official specification.
All the MMC_RESPONSE_R(_x) are replaced with each corresponding define.

Signed-off-by: Lionel Debieve <lionel.debieve@st.com>
Signed-off-by: Yann Gautier <yann.gautier@st.com>

### CODE REVIEW

**Comment by antonio-nino-diaz-arm** [comment]
IP Review +1

**Comment by Yann-lms** [comment]
@shawnguo2 @bryanodonoghue @niej @hzhuang1 could you check this patch on your side?

**Comment by shawnguo2** [comment]
I get the following build error on Poplar.
```
drivers/synopsys/emmc/dw_mmc.c: In function ‘dw_send_cmd’:
drivers/synopsys/emmc/dw_mmc.c:269:2: error: duplicate case value
  case MMC_RESPONSE_R5:
  ^~~~
drivers/synopsys/emmc/dw_mmc.c:266:2: note: previously used here
  case MMC_RESPONSE_R1:
  ^~~~
make: *** [build/poplar/debug/bl1/dw_mmc.o] Error 1
```

**Comment by Yann-lms** [comment]
My bad I forgot to remove those lines in the dw_mmc driver. I've pushed a new commit, could you check it?

**Comment by hzhuang1** [comment]
It works fine on hikey.
Acked.

**Comment by shawnguo2** [comment]
Tested on Poplar, thanks.

**Comment by bryanodonoghue** [comment]
Fine on WaRP7
Tested-by: Bryan O'Donoghue <bryan.odonoghue@linaro.org>

**Pull request merged**
