### PR TITLE
Update SPM/DCM related code for power control

### PR DESCRIPTION
**Pull request by mtk09422**
previous review https://github.com/ARM-software/arm-trusted-firmware/pull/392

### CODE REVIEW

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by danh-arm** [comment]
test this please

**Comment by achingupta** [comment]
Hi,

We are seeing the following build error in our CI loop. Could you please rectify it.

``
  CC      plat/mediatek/board/common/param_init.c
aarch64-linux-gnu-gcc -g -nostdinc -ffreestanding -Wall -Werror -Wmissing-include-dirs -mgeneral-regs-only -mstrict-align -std=c99 -c -Os -DDEBUG=1 -DARM_GIC_ARCH=2 -DSKIP_A57_L1_FLUSH_PWR_DWN=0 -DERRATA_A53_826319=1 -DERRATA_A53_836870=1 -DERRATA_A57_806969=0 -DERRATA_A57_813420=0 -DPLAT_mt8173 -DNS_TIMER_SWITCH=0 -DRESET_TO_BL31=0 -DCTX_INCLUDE_FPREGS=0 -DARM_GIC_ARCH=2 -DARM_CCI_PRODUCT_ID=400 -DASM_ASSERTION=1 -DLOG_LEVEL=40 -DUSE_COHERENT_MEM=1 -DTRUSTED_BOARD_BOOT=0 -DPROGRAMMABLE_RESET_ADDRESS=1 -DPSCI_EXTENDED_STATE_ID=0 -DWARN_DEPRECATED=0 -DENABLE_PLAT_COMPAT=1 -DIMF_READ_INTERRUPT_ID=0 -DCRASH_REPORTING=1 -Iinclude/bl31 -Iinclude/bl31/services -Iinclude/common -Iinclude/drivers -Iinclude/drivers/arm -Iinclude/drivers/auth -Iinclude/drivers/io -Iinclude/drivers/ti/uart -Iinclude/lib -Iinclude/lib/aarch64 -Iinclude/lib/cpus/aarch64 -Iinclude/plat/common -Iinclude/stdlib -Iinclude/stdlib/sys -Iplat/mediatek/soc/common/ -Iplat/mediatek/soc/mt8173/drivers/gpio/ -Iplat/mediatek/soc/mt8173/drivers/i2c/ -Iplat/mediatek/soc/mt8173/drivers/mtcmos/ -Iplat/mediatek/soc/mt8173/drivers/pmic/ -Iplat/mediatek/soc/mt8173/drivers/rtc/ -Iplat/mediatek/soc/mt8173/drivers/spm/ -Iplat/mediatek/soc/mt8173/drivers/timer/ -Iplat/mediatek/soc/mt8173/drivers/uart/ -Iplat/mediatek/soc/mt8173/include/ -Iplat/mediatek/board/common/drivers/include -Iplat/mediatek/board/common/include  -ffunction-sections -fdata-sections -pedantic -DIMAGE_BL31 -c plat/mediatek/board/common/param_init.c -o build/mt8173/debug/bl31/param_init.o
plat/mediatek/board/common/param_init.c:44:13: error: ISO C forbids empty initializer braces [-Werror=pedantic]
 } bucks[] = {
             ^
plat/mediatek/board/common/param_init.c:44:3: error: zero or negative size array 'bucks'
 } bucks[] = {
   ^
cc1: all warnings being treated as errors
make: *** [build/mt8173/debug/bl31/param_init.o] Error 1
``
It is the same for PR #433 as well.

hth,
Achin

**Comment by mtk09422** [comment]
https://github.com/ARM-software/arm-trusted-firmware/pull/436 and https://github.com/ARM-software/arm-trusted-firmware/pull/437 fix this compilation error,

**Pull request closed without merging**
