### PR TITLE
Library archives

### PR DESCRIPTION
**Pull request by robertovargas-arm**
These patches modify the build system adding the possibility of creating library archives instead of selecting individual files of the library source.

### CODE REVIEW

**Comment by masahir0y** [comment]
What is the benefit of this change set?

**Comment by robertovargas-arm** [comment]
This is the first part of the set of changes oriented to place libraries at ROM to minimize the amount of SRAM used. Having the libraries as actual library archives makes easier to enable or disable that feature.

**Comment by antonio-nino-diaz-arm** [comment]
Just a detail, the name of the library isn't "libmbedtls" but "Mbed TLS", you should change the commit message.

**Comment by robertovargas-arm** [comment]
Mbed TLS is the name of the project as it is reported in the body of the commit message, but the name of the library archive file is libmbedtls, in the same way that the C library is libc, and the fdt library is libfdt.

**Comment by antonio-nino-diaz-arm** [comment]
Yeah, but the commit message says "Create library file for <library X>" where <library X> = {libc, libfdt, Mbed TLS}.

**Comment by antonio-nino-diaz-arm** [comment]
Ok, let's discuss this later. It's just a detail anyway.

**Comment by dp-arm** [comment]
jenkins: test this please

**Comment by dp-arm** [comment]
jenkins: test this please

**Comment by danh-arm** [comment]
I'm closing this. A new PR will be submitted later with additional patches that do something useful.

**Pull request closed without merging**
