### PR TITLE
Tegra new platform apis v1

### PR DESCRIPTION
**Pull request by vwadekar**
Switch to the new platform APIs so that we are not dependent on the platform compatibility layer.

Previous PR - #440

### CODE REVIEW

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by soby-mathew** [comment]
@vwadekar,
Hi Varun, 
   I had a review of the PR and it seems fine to me.

Best Regards
Soby Mathew

**Comment by vwadekar** [comment]
Thanks Soby

**Comment by danh-arm** [comment]
test this please

**Comment by danh-arm** [comment]
Hi Varun. I've just noticed this PR targets the master branch, not the integration branch. Could you please create a new one then I will merge. Cheers, Dan.

**Comment by danh-arm** [comment]
This also has a build error in our CI:
```
Build options: CROSS_COMPILE=aarch64-linux-gnu- V=1 PLAT=tegra TARGET_SOC=t132
```

```
CC      plat/nvidia/tegra/soc/t132/plat_psci_handlers.c
aarch64-linux-gnu-gcc -nostdinc -ffreestanding -Wall -Werror -Wmissing-include-dirs -mgeneral-regs-only -mstrict-align -std=c99 -c -Os -DDEBUG=0 -DNDEBUG -DCRASH_REPORTING=1 -DASM_ASSERTION=1 -DTEGRA_BOOT_UART_BASE=0x70006300 -DTZDRAM_BASE=0xF5C00000 -DPLATFORM_CLUSTER_COUNT=1 -DPLATFORM_MAX_CPUS_PER_CLUSTER=2 -DSKIP_A57_L1_FLUSH_PWR_DWN=0 -DERRATA_A53_826319=0 -DERRATA_A53_836870=0 -DERRATA_A57_806969=0 -DERRATA_A57_813420=0 -DPLAT_tegra -DNS_TIMER_SWITCH=0 -DRESET_TO_BL31=0 -DCTX_INCLUDE_FPREGS=0 -DARM_GIC_ARCH=2 -DARM_CCI_PRODUCT_ID=400 -DASM_ASSERTION=1 -DLOG_LEVEL=20 -DUSE_COHERENT_MEM=0 -DTRUSTED_BOARD_BOOT=0 -DPROGRAMMABLE_RESET_ADDRESS=0 -DCOLD_BOOT_SINGLE_CPU=0 -DPSCI_EXTENDED_STATE_ID=0 -DERROR_DEPRECATED=0 -DENABLE_PLAT_COMPAT=0 -DSPIN_ON_BL1_EXIT=0 -DCRASH_REPORTING=1 -Iinclude/bl31 -Iinclude/bl31/services -Iinclude/common -Iinclude/drivers -Iinclude/drivers/arm -Iinclude/drivers/auth -Iinclude/drivers/io -Iinclude/drivers/ti/uart -Iinclude/lib -Iinclude/lib/aarch64 -Iinclude/lib/cpus/aarch64 -Iinclude/plat/common -Iinclude/stdlib -Iinclude/stdlib/sys -Iplat/nvidia/tegra/include/drivers -Iplat/nvidia/tegra/include -Iplat/nvidia/tegra/include/t132  -ffunction-sections -fdata-sections -pedantic -Wno-error=deprecated-declarations -DIMAGE_BL31 -c plat/nvidia/tegra/soc/t132/plat_psci_handlers.c -o build/tegra/t132/release/bl31/plat_psci_handlers.o
plat/nvidia/tegra/soc/t132/plat_psci_handlers.c: In function 'tegra_soc_pwr_domain_suspend':
plat/nvidia/tegra/soc/t132/plat_psci_handlers.c:139:6: error: unused variable 'cpu' [-Werror=unused-variable]
  int cpu = read_mpidr() & MPIDR_CPU_MASK;
      ^
cc1: all warnings being treated as errors
make: *** [build/tegra/t132/release/bl31/plat_psci_handlers.o] Error 1
Build failed with code 2
```

**Comment by vwadekar** [comment]
Sorry about that. Will push a new one today

**Comment by vwadekar** [comment]
New PR - #452

**Pull request closed without merging**
