### PR TITLE
MISRA 5.1, 5.3 & 5.7 compliance changes

### PR DESCRIPTION
**Pull request by danielboulby-arm**
Changes to make the code base compliant with MISRA rules 5.1, 5.3 & 5.7

### CODE REVIEW

**Comment by danh-arm** [comment]
jenkins: retest this please

**Comment by danielboulby-arm** [comment]
The MISRA violations flagged up in this PR are violations that we have not yet got round to fixing and have been reflagged due to the renaming of some functions. These violations will be fixed with the others of the same rule

**Comment by dp-arm** [comment]
jenkins: test this please

**Comment by dp-arm** [comment]
jenkins: test this please

**Pull request merged**
