### PR TITLE
CPUECTLR_EL1 and L2ECTLR_EL1 retention timer ticks

### PR DESCRIPTION
**Pull request by vwadekar**
*  	CPUECTLR_EL1 and L2ECTLR_EL1 retention control masks
* 	Tegra: wait for 512 timer ticks before retention entry

### CODE REVIEW

**Comment by vwadekar** [comment]
Previous PR #369

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by danh-arm** [comment]
Looks good to me!

**Comment by danh-arm** [comment]
test this please

**Comment by vwadekar** [comment]
@danh-arm 

Thanks Dan.

**Comment by vwadekar** [comment]
New PR - #371

**Pull request closed without merging**
