### PR TITLE
Tegra new platform apis v2

### PR DESCRIPTION
**Pull request by vwadekar**
Support for new platform APIs. Deprecate support for the PLAT_COMPAT layer.

Previous PR - #450

### CODE REVIEW

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by danh-arm** [comment]
test this please

**Comment by vwadekar** [comment]
Thanks Dan

**Pull request merged**
