### PR TITLE
Tegra: support PSCI v1.0 framework implementation

### PR DESCRIPTION
**Pull request by vwadekar**
This patch modifies the Tegra port to support the new PSCI v1.0
implementation. This includes modifications to the power management
and platform topology code.

Signed-off-by: Varun Wadekar <vwadekar@nvidia.com>

### CODE REVIEW

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by vwadekar** [comment]
Previous PR - #366

**Comment by vwadekar** [comment]
@soby-mathew 

Hello Soby,

I have fixed your comments with this new PR. Please let me know if there's any feedback.

Thanks.

**Comment by soby-mathew** [comment]
@vwadekar,
Thanks Varun. I will take a look and get back to you.

**Comment by soby-mathew** [comment]
@vwadekar,
Hi Varun,
Major comments are wrt to the topology description of T210 platform. Also the cpu index calculation need to be modified if the suggested description is used.

The state-id parsing and req_state[] populating are done as intended. I have given some comments on how it can be improved. I had some doubts on the PSTATE_ID_CLUSTER_IDLE state ID. If it is indeed a retention state as the name suggests, then by classifying it as a retention state to the PSCI generic layer will be a huge optimization for that state. See my comments for more details.

**Comment by vwadekar** [comment]
@soby-mathew 

Thanks Soby. Will work on the feedback. The PSTATE_ID_CLUSTER_IDLE state is not a retention state - the name is indeed misleading, but is a shallower state than PSTATE_ID_CLUSTER_POWERDOWN.

**Comment by vwadekar** [comment]
New Pr - #378

**Pull request closed without merging**
