### PR TITLE
MMU improvements v1

### PR DESCRIPTION
**Pull request by lumag**
Proposed fix for https://github.com/ARM-software/tf-issues/issues/362

- Large page size support.
- Optional 4th level translation support.

### CODE REVIEW

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by danh-arm** [comment]
On hold pending a plan to the issues raised in https://github.com/ARM-software/tf-issues/issues/362.

**Comment by danh-arm** [comment]
Hi @lumag 

Are you planning to rework this to only address the 4 level translation table support? Note this code has changed recently and more changes are coming, so you will need to rebase.

**Comment by lumag** [comment]
@danh-arm, I was dragged away by current development tasks, but I surely
plan to address this issue.

**Comment by danh-arm** [comment]
I'm closing this since 4 level translation table support is now implemented by https://github.com/ARM-software/arm-trusted-firmware/commit/e8719552a243b7e7e0d2fd3401669e68c9519170.

**Pull request closed without merging**
