### PR TITLE
Change some vars and functions to be static.

### PR DESCRIPTION
**Pull request by laroche**
Signed-off-by: Florian La Roche <Florian.LaRoche@gmail.com>

### CODE REVIEW

**Comment by laroche** [comment]
I think noone is using "list" from partition.c, but I have only verified this by a "grep" that had many occurances. The change to ufs should be easy to verify.

**Comment by antonio-nino-diaz-arm** [comment]
Just a nit: commit titles don't end with a dot. Don't bother changing it in this one, though.

IP Review +1

**Comment by antonio-nino-diaz-arm** [comment]
jenkins: test this please

**Comment by antonio-nino-diaz-arm** [comment]
The CI failures are infrastructure issues.

**Pull request merged**
