### PR TITLE
Clean up __attribute__ usage

### PR DESCRIPTION
**Pull request by sorenb-xlnx**
Move common compiler-specific macros into a generic, common header.

Fixes ARM-software/tf-issues#340

Signed-off-by: Soren Brinkmann <soren.brinkmann@xilinx.com>

### CODE REVIEW

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by danh-arm** [comment]
I added a comment to ARM-software/tf-issues#340 stating what we expect this fix to look like.

**Comment by sorenb-xlnx** [comment]
Should I keep and update this PR? Or rather close this and create a new
one with the updated fix?

	Sören

**Comment by danh-arm** [comment]
I don't mind either way. Given that there are no significant comments against your initial patch, you can just update this PR. We only ask that people create new PRs if the patch(es) contain comments that we don't want to lose (which happens if you force push to a PR's topic branch).

**Comment by sorenb-xlnx** [comment]
I updated the branch as outlined in the bug report.

**Comment by danh-arm** [comment]
test this please

**Comment by danh-arm** [comment]
Looks good. Thanks.

**Pull request merged**
