### PR TITLE
rcar_gen3: plat: Add R-Car V3M support

### PR DESCRIPTION
**Pull request by marex**
Add R-Car V3M support. This is based on the original
V3M support patch for Yocto v2.23.1 by Vladimir Barinov.

Signed-off-by: Vladimir Barinov <vladimir.barinov@cogentembedded.com>
Signed-off-by: Valentine Barshak <valentine.barshak@cogentembedded.com>
Signed-off-by: Marek Vasut <marek.vasut+renesas@gmail.com>
---
Marek: Update on top of mainline ATF/master

### CODE REVIEW

**Comment by antonio-nino-diaz-arm** [comment]
IP Review +1

**Comment by antonio-nino-diaz-arm** [comment]
jenkins: test this please

**Comment by antonio-nino-diaz-arm** [comment]
The only failures are checkpatch.pl errors in ``drivers/staging``.

**Comment by antonio-nino-diaz-arm** [comment]
By the way, could you copy here a sample command line to build this platform so that I add it to the CI?

**Comment by marex** [comment]
On 4/3/19 10:35 AM, Antonio Niño Díaz wrote:
> By the way, could you copy here a sample command line to build this
> platform so that I add it to the CI?

make -j9 bl2 bl31 rcar PLAT=rcar LSI=V3M MACHINE=eagle RCAR_DRAM_SPLIT=0
PMIC_ROHM_BD9571=0 RCAR_SYSTEM_SUSPEND=0 AVS_SETTING_ENABLE=0 SPD=none
RCAR_BL33_EXECUTION_EL=1 LOG_LEVEL=50 DEBUG=0 RCAR_RPC_HYPERFLASH_LOCKED=0

The whole test matrix is at:
https://travis-ci.org/marex/arm-trusted-firmware-1/builds/514687523/config

Documentation here:
https://elinux.org/R-Car/Boards/ATF-Gen3

-- 
Best regards,
Marek Vasut

**Comment by antonio-nino-diaz-arm** [comment]
Is this configuration meant to fail?
```
    - name: "R-Car R8A77970/V3M Eagle"
      env:
        - BUILD_ELF="${RCAR_BUILD_ELF}"
        - BUILD_TRG="${RCAR_BUILD_TRG}"
        - BUILD_OPT="LSI=V3M MACHINE=eagle ${RCAR_OPT_COMMON} ${RCAR_OPT_V3X}"
```
I get:
```
plat/renesas/rcar/platform.mk:182: *** "Error: V3H is not supported.".  Stop.
```

**Comment by antonio-nino-diaz-arm** [comment]
I've updated our CI with the other build configs. I'll leave the condor one out for now.

**Comment by marex** [comment]
On 4/3/19 2:56 PM, Antonio Niño Díaz wrote:
> Is this configuration meant to fail?
> 
> |- name: "R-Car R8A77970/V3M Eagle" env: - BUILD_ELF="${RCAR_BUILD_ELF}"
> - BUILD_TRG="${RCAR_BUILD_TRG}" - BUILD_OPT="LSI=V3M MACHINE=eagle
> ${RCAR_OPT_COMMON} ${RCAR_OPT_V3X}" |
> 
> I get:
> 
> |plat/renesas/rcar/platform.mk:182: *** "Error: V3H is not supported.".
> Stop. |

How can you get "V3H is not supported" with LSI=V3M ? I think you mixed
V3H and V3M somewhere in your test.

-- 
Best regards,
Marek Vasut

**Comment by antonio-nino-diaz-arm** [comment]
Sorry, I updated the message and it looks like GitHub doesn't send email notifications in that case:
```
    - name: "R-Car R8A77980/V3H Condor"
      env:
        - BUILD_ELF="${RCAR_BUILD_ELF}"
        - BUILD_TRG="${RCAR_BUILD_TRG}"
        - BUILD_OPT="LSI=V3H MACHINE=condor RCAR_SECURE_BOOT=0 ${RCAR_OPT_COMMON} ${RCAR_OPT_V3X}"

```

**Comment by marex** [comment]
On 4/3/19 4:05 PM, Antonio Niño Díaz wrote:
> Sorry, I updated the message and it looks like GitHub doesn't send email
> notifications in that case:
> 
> |- name: "R-Car R8A77980/V3H Condor" env: -
> BUILD_ELF="${RCAR_BUILD_ELF}" - BUILD_TRG="${RCAR_BUILD_TRG}" -
> BUILD_OPT="LSI=V3H MACHINE=condor RCAR_SECURE_BOOT=0 ${RCAR_OPT_COMMON}
> ${RCAR_OPT_V3X}" |

V3H Condor is not supported upstream yet, only V3M Eagle is supported
thus far.

-- 
Best regards,
Marek Vasut

**Comment by antonio-nino-diaz-arm** [comment]
Ok, thanks.

**Pull request merged**
