### PR TITLE
Mt8173 support v2

### PR DESCRIPTION
**Pull request by mtk09422**
previous review https://github.com/ARM-software/arm-trusted-firmware/pull/298

### CODE REVIEW

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by danh-arm** [comment]
test this please

**Comment by danh-arm** [comment]
Apart from the possible delay timer issue, this looks OK to me!

**Comment by danh-arm** [comment]
retest this please

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by jcastillo-arm** [comment]
retest this please

**Comment by danh-arm** [comment]
retest this please

**Comment by jimmyh-mtk** [comment]
We already updated the copyright and license header. The plat_timerus_get_value() was also changed to plat_get_timer_value(). Sorry for I didn't find your message here earlier.

**Pull request closed without merging**
