### PR TITLE
New framework to support PSCI v1.0 optional features

### PR DESCRIPTION
**Pull request by achingupta**
This patch-set introduces the new framework to better support the power
domain topology and composite power state as specified in PSCI v1.0
specification. PSCI v1.0 mandatory features are already supported in
ARM Trusted Firmware and this patch-set improves support for the
optional features and reduces complexity for platform ports.

As a result of these framework changes, the platform API has changed
as well. A platform compatibility layer is implemented to ensure that the
existing platform ports using the old platform API will continue to work
with minimal changes. Care is also taken to enable the SPDs to
continue to work even if the compatibility layer is disabled.

Supersedes PR #355 

Changes from #355 :
*  It was not mandatory for old platform ports to populate the `validate_power_state()` hook in the `plat_pm_ops_t` structure. This hook is mandatory in the new platform porting interface in the `plat_psci_ops_t` structure. The compatibility layer was treating this hook as optional even with the new porting interface. This bug has been rectified in this pull request. Also, the old hook is called only if has been exported by the old platform ports.

### CODE REVIEW

**Comment by vwadekar** [comment]
@achingupta 

Hello Achin,

I see the following assert on Tegra platforms if I define PLATFORM_MAX_AFFLVL as MPIDR_AFFLVL2.

    64NOTICE:  BL3-1: v1.1(debug):2a1747d
    NOTICE:  BL3-1: Built : 17:39:17, Aug 11 2015
    INFO:    Setting up secondary CPU boot
    INFO:    Configuring SMMU
    INFO:    Configuring TrustZone DRAM Memory Carveout
    INFO:    BL3-1: Initializing runtime services
    ASSERT: platform_get_power_domain_tree_desc <178> : affmap_idx == (PLATFORM_NUM_AFFS - PLATFORM_CORE_COUNT + 1)

Is this expected? Changing it to MPIDR_AFFLVL1 makes the assert go away.

**Comment by achingupta** [comment]
@vwadekar @danh-arm 

Hi Varun,

Let me have a look and get back to you by tomorrow at the latest. Hope that is ok?

Thanks,
Achin

**Comment by achingupta** [comment]
@vwadekar @danh-arm 

FWIW, `init_pwr_domain_tree_desc()` in `plat_topology_compat.c` relies on the old platform API `plat_get_aff_count()` to create the power domain topology tree. If there is a discrepancy between the macros you mentioned and what this API reports then this assert is likely to fire. I will have a closer look later.

Thanks,
Achin

**Comment by vwadekar** [comment]
@achingupta 

Thanks Achin. Since the Tegra topology code is going to change completely once Tegra supports this PR, does it make sense to discount this assert for now since we have #360 in the pipeline?

**Comment by danh-arm** [comment]
@vwadekar @achingupta 
I've not convinced by the fix in #360. We need to get to the bottom of the assert before merging this PR (#359) in case there are other (unseen) platforms that get broken by it.

**Comment by vwadekar** [comment]
Thanks Dan. Will debug this issue tomorrow.

**Comment by achingupta** [comment]
@danh-arm , @vwadekar 

I cannot see why both the set of macros i.e. the existing ones in the Tegra port that include support for the system level power domain and the new ones which do not should not work. I have even tried enabling the compatibility layer on Juno with the maximum affinity level as 2. This was done on commit https://github.com/achingupta/arm-trusted-firmware/commit/080d4948285987ac0a61da04969f95438a105ae9 using the following patch:
```
diff --git a/include/plat/arm/common/arm_def.h b/include/plat/arm/common/arm_def.h
index 4447af2..ed6b293 100644
--- a/include/plat/arm/common/arm_def.h
+++ b/include/plat/arm/common/arm_def.h
@@ -164,8 +164,8 @@
 #define ADDR_SPACE_SIZE                        (1ull << 32)

 #define PLATFORM_NUM_AFFS              (ARM_CLUSTER_COUNT + \
-                                        PLATFORM_CORE_COUNT)
-#define PLATFORM_MAX_AFFLVL            MPIDR_AFFLVL1
+                                        PLATFORM_CORE_COUNT + 1)
+#define PLATFORM_MAX_AFFLVL            MPIDR_AFFLVL2

 #define PLATFORM_CORE_COUNT            (PLAT_ARM_CLUSTER0_CORE_COUNT + \
                                         PLAT_ARM_CLUSTER1_CORE_COUNT)
diff --git a/plat/compat/plat_topology_compat.c b/plat/compat/plat_topology_compat.c
index fee7ae1..b11f5d0 100644
--- a/plat/compat/plat_topology_compat.c
+++ b/plat/compat/plat_topology_compat.c
@@ -33,6 +33,7 @@
 #include <platform.h>
 #include <platform_def.h>
 #include <psci.h>
+#include <debug.h>

 /* The power domain tree descriptor */
 static unsigned char power_domain_tree_desc
@@ -149,6 +150,7 @@ static unsigned int init_pwr_domain_tree_desc(unsigned long mpidr,
                }
        } else {
                power_domain_tree_desc[affmap_idx++] = aff_count;
+               tf_printf("affmap_idx = %d \n", affmap_idx);
        }
        return affmap_idx;
 }
```
The values of `affmap_idx` printed in this case are:
```
affmap_idx = 1 
affmap_idx = 2 
affmap_idx = 3 
affmap_idx = 4 
```
The values of `affmap_idx` printed without the macro changes are:
```
affmap_idx = 1 
affmap_idx = 2 
affmap_idx = 3 
```
Both are correct afaics. In the first case, the value of `PLATFORM_NUM_AFFS - PLATFORM_CORE_COUNT + 1` will be `9 - 6 + 1` while in the second case it will be `8 - 6 + 1`.

Varun. Could you let us know what are you seeing at your end?

Thanks,
Achin

**Comment by vwadekar** [comment]
@danh-arm @achingupta 

Adding prints yielded the following results -

'''
INFO:    affmap_idx = 1
INFO:    affmap_idx = 2
INFO:    affmap_idx = 3
INFO:    affmap_idx = 4
ASSERT: platform_get_power_domain_tree_desc <180> : affmap_idx ==     (PLATFORM_NUM_AFFS - PLATFORM_CORE_COUNT + 1)
'''
But, with the following changes I do not hit the assert.
'''
#define PLATFORM_MAX_AFFLVL		MPIDR_AFFLVL2
#define PLATFORM_CORE_COUNT		(PLATFORM_CLUSTER_COUNT * \
					 PLATFORM_MAX_CPUS_PER_CLUSTER)
#define PLATFORM_NUM_AFFS		(PLATFORM_CORE_COUNT + \
					 PLATFORM_CLUSTER_COUNT + 1)
'''
Changing PLATFORM_NUM_AFFS did the trick! I had to add **1** to the number of affinities to accommodate MPIDR_AFFLVL2.

**Comment by achingupta** [comment]
@vwadekar 

Thanks for the confirmation. I am renaming a few platform porting interfaces. I will push out an update later in the day. You will have to update the Tegra port branch which uses the new porting interface. Not urgent but just an FYI. We should be able to merge this PR tomorrow.

**Comment by vwadekar** [comment]
Thanks Achin. Will update the Tegra changes once I take a look at the
renamed functions.

**Comment by achingupta** [comment]
Superseded by #361

**Pull request closed without merging**
