### PR TITLE
hikey960: set isp clks as unsecure mode

### PR DESCRIPTION
**Pull request by hzhuang1**
Signed-off-by: Haojian Zhuang <haojian.zhuang@linaro.org>

### CODE REVIEW

**Comment by davidcunado-arm** [comment]
jenkins: please test this

**Comment by davidcunado-arm** [comment]
jenkins: test this please

**Comment by hzhuang1** [comment]
Could this patch be merged? Thanks

**Comment by soby-mathew** [comment]
@hzhuang1, we hope to have this merged next week as team members are on holiday this week.

**Pull request merged**
