### PR TITLE
hikey960: EDMAC: leave channel 0 as secure

### PR DESCRIPTION
**Pull request by oscardagrach**
Channel 0 is used to communicate with the LPM3 CPU onboard,
leave it as secure.

Signed-off-by: Ryan Grachek <ryan@edited.us>

### CODE REVIEW

**Comment by antonio-nino-diaz-arm** [comment]
IP Review +1

**Comment by antonio-nino-diaz-arm** [comment]
jenkins: test this please

**Comment by antonio-nino-diaz-arm** [comment]
@hzhuang1 we will merge this this week if there are no comments from your side. If needed we could always revert it in the future.

**Comment by antonio-nino-diaz-arm** [comment]
Ok, thanks

**Comment by antonio-nino-diaz-arm** [comment]
jenkins: test this please

**Comment by antonio-nino-diaz-arm** [comment]
This fails to build because of ``-Werror``:
```
make  CROSS_COMPILE=aarch64-linux-gnu- PLAT=hikey960  DEBUG=1 V=1 fiptool all
```
This is the failure:
```
In file included from plat/hisilicon/hikey960/hikey960_bl31_setup.c:25:0:
plat/hisilicon/hikey960/hikey960_bl31_setup.c: In function 'hikey960_iomcu_dma_init':
plat/hisilicon/hikey960/include/hi3660.h:378:54: error: suggest parentheses around '+' inside '<<' [-Werror=parentheses]
 #define IOMCU_DMAC_AXI_CONF(x)   (EDMAC_BASE + 0x820 + (x) << 6))
                                                      ^
plat/hisilicon/hikey960/hikey960_bl31_setup.c:173:17: note: in expansion of macro 'IOMCU_DMAC_AXI_CONF'
   mmio_write_32(IOMCU_DMAC_AXI_CONF(i), (1 << 6) | (1 << 18));
                 ^~~~~~~~~~~~~~~~~~~
plat/hisilicon/hikey960/hikey960_bl31_setup.c:173:3: error: too few arguments to function 'mmio_write_32'
   mmio_write_32(IOMCU_DMAC_AXI_CONF(i), (1 << 6) | (1 << 18));
   ^~~~~~~~~~~~~
In file included from plat/hisilicon/hikey960/hikey960_bl31_setup.c:22:0:
include/lib/mmio.h:39:20: note: declared here
 static inline void mmio_write_32(uintptr_t addr, uint32_t value)
                    ^~~~~~~~~~~~~
plat/hisilicon/hikey960/hikey960_bl31_setup.c:173:39: error: left-hand operand of comma expression has no effect [-Werror=unused-value]
   mmio_write_32(IOMCU_DMAC_AXI_CONF(i), (1 << 6) | (1 << 18));
                                       ^
plat/hisilicon/hikey960/hikey960_bl31_setup.c:173:39: error: statement with no effect [-Werror=unused-value]
plat/hisilicon/hikey960/hikey960_bl31_setup.c:173:61: error: expected ';' before ')' token
   mmio_write_32(IOMCU_DMAC_AXI_CONF(i), (1 << 6) | (1 << 18));
                                                             ^
plat/hisilicon/hikey960/hikey960_bl31_setup.c:173:61: error: expected statement before ')' token
cc1: all warnings being treated as errors
Makefile:741: recipe for target 'build/hikey960/debug/bl31/hikey960_bl31_setup.o' failed
make: *** [build/hikey960/debug/bl31/hikey960_bl31_setup.o] Error 1
```

**Comment by antonio-nino-diaz-arm** [comment]
Also, while you are on it, can you rebase on the current master?

**Comment by oscardagrach** [comment]
@antonio-nino-diaz-arm I'm going to close this pull request and open a new one. My local repo was a mess and some code snuck in there that wasn't ready to be pushed. I don't want there to be any confusion and will do a clean pull request.

**Pull request closed without merging**
