### PR TITLE
Set alignment size to 512B for Hikey/Hikey960

### PR DESCRIPTION
**Pull request by Leo-Yan**
These two patches are to set alignment size to 512B for Hikey/Hikey960, as results we can generate the fip.bin with 512B alignment and ensure it's safe for USB downloading with DMA enabled.

### CODE REVIEW

**Comment by Leo-Yan** [comment]
Hi @hzhuang1, please review this patch. Thanks.

**Comment by hzhuang1** [comment]
@Leo-Yan acked

**Comment by davidcunado-arm** [comment]
jenkins: test this please

**Comment by robertovargas-arm** [comment]
I and @geesun are tracking a problem in [https://github.com/ARM-software/tf-issues/issues/528](url), and in some cases it can generate unaligned access and incorrect reads when the size of the read isn't a multiple of the block size. We still have to look if both problems are related, but it is very likely.

Anyway, it seems that the solution in this PR is a workaround and instead of fixing the actual problem is hiding it.

**Comment by davidcunado-arm** [comment]
@Leo-Yan 
I've now merged #1204 into integration - please let me know whether this PR can be merged as is or you're planning on changing the alignment value (as per your comment in #1204).

**Comment by Leo-Yan** [comment]
Hi @davidcunado-arm, I have consolidate with Haojian, we prefer to use 512B as alignment size. So please help merge this PR. Thanks.

**Comment by davidcunado-arm** [comment]
@Leo-Yan 
Ok looking to merge this now that I've merged the fip padding change is now in master.

**Comment by davidcunado-arm** [comment]
jenkins: test this please

**Pull request merged**
