### PR TITLE
Tegra new platform apis

### PR DESCRIPTION
**Pull request by vwadekar**
Move to the new platform porting APIs for Tegra, so that we no longer use the platform_compat layer.

### CODE REVIEW

**Comment by vwadekar** [comment]
Previous PR - #379

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by vwadekar** [comment]
@danh-arm @achingupta 

Hello,

Any feedback?

**Comment by danh-arm** [comment]
test this please

**Comment by danh-arm** [comment]
Sorry Varun. Achin's not available this week and I've been looking at lots of other internal patches. Is this urgent for you? If so, I'll get someone else onto it.

**Comment by vwadekar** [comment]
Thanks Dan. It's not urgent. Will you be able to spend some time this week?

**Comment by danh-arm** [comment]
There was 1 checkpatch error in this. Some of the warnings are easy to fix too:
```
CHECKING STYLE
WARNING: added, moved or deleted file(s), does MAINTAINERS need updating?
#1313: 
new file mode 100644

WARNING: Missing a blank line after declarations
#1362: FILE: drivers/arm/gic/v2/gicv2_helpers.c:45:
+	unsigned n = id >> ITARGETSR_SHIFT;
+	return mmio_read_32(base + GICD_ITARGETSR + (n << 2));

WARNING: Missing a blank line after declarations
#1372: FILE: drivers/arm/gic/v2/gicv2_helpers.c:55:
+	unsigned n = id >> CPENDSGIR_SHIFT;
+	return mmio_read_32(base + GICD_CPENDSGIR + (n << 2));

WARNING: Missing a blank line after declarations
#1382: FILE: drivers/arm/gic/v2/gicv2_helpers.c:65:
+	unsigned n = id >> SPENDSGIR_SHIFT;
+	return mmio_read_32(base + GICD_SPENDSGIR + (n << 2));

WARNING: Missing a blank line after declarations
#1392: FILE: drivers/arm/gic/v2/gicv2_helpers.c:75:
+	unsigned n = id >> ITARGETSR_SHIFT;
+	mmio_write_32(base + GICD_ITARGETSR + (n << 2), val);

WARNING: Missing a blank line after declarations
#1402: FILE: drivers/arm/gic/v2/gicv2_helpers.c:85:
+	unsigned n = id >> CPENDSGIR_SHIFT;
+	mmio_write_32(base + GICD_CPENDSGIR + (n << 2), val);

WARNING: Missing a blank line after declarations
#1412: FILE: drivers/arm/gic/v2/gicv2_helpers.c:95:
+	unsigned n = id >> SPENDSGIR_SHIFT;
+	mmio_write_32(base + GICD_SPENDSGIR + (n << 2), val);

WARNING: Missing a blank line after declarations
#1687: FILE: drivers/arm/gic/v2/gicv2_main.c:134:
+	unsigned int gic_version;
+	assert(plat_driver_data);

WARNING: do not add new typedefs
#2108: FILE: include/drivers/arm/gicv2.h:142:
+typedef struct gicv2_driver_data {

WARNING: Missing a blank line after declarations
#2209: FILE: drivers/arm/gic/common/gic_common.c:45:
+	unsigned n = id >> IGROUPR_SHIFT;
+	return mmio_read_32(base + GICD_IGROUPR + (n << 2));

WARNING: Missing a blank line after declarations
#2219: FILE: drivers/arm/gic/common/gic_common.c:55:
+	unsigned n = id >> ISENABLER_SHIFT;
+	return mmio_read_32(base + GICD_ISENABLER + (n << 2));

WARNING: Missing a blank line after declarations
#2229: FILE: drivers/arm/gic/common/gic_common.c:65:
+	unsigned n = id >> ICENABLER_SHIFT;
+	return mmio_read_32(base + GICD_ICENABLER + (n << 2));

WARNING: Missing a blank line after declarations
#2239: FILE: drivers/arm/gic/common/gic_common.c:75:
+	unsigned n = id >> ISPENDR_SHIFT;
+	return mmio_read_32(base + GICD_ISPENDR + (n << 2));

WARNING: Missing a blank line after declarations
#2249: FILE: drivers/arm/gic/common/gic_common.c:85:
+	unsigned n = id >> ICPENDR_SHIFT;
+	return mmio_read_32(base + GICD_ICPENDR + (n << 2));

WARNING: Missing a blank line after declarations
#2259: FILE: drivers/arm/gic/common/gic_common.c:95:
+	unsigned n = id >> ISACTIVER_SHIFT;
+	return mmio_read_32(base + GICD_ISACTIVER + (n << 2));

WARNING: Missing a blank line after declarations
#2269: FILE: drivers/arm/gic/common/gic_common.c:105:
+	unsigned n = id >> ICACTIVER_SHIFT;
+	return mmio_read_32(base + GICD_ICACTIVER + (n << 2));

WARNING: Missing a blank line after declarations
#2279: FILE: drivers/arm/gic/common/gic_common.c:115:
+	unsigned n = id >> IPRIORITYR_SHIFT;
+	return mmio_read_32(base + GICD_IPRIORITYR + (n << 2));

WARNING: Missing a blank line after declarations
#2289: FILE: drivers/arm/gic/common/gic_common.c:125:
+	unsigned n = id >> ICFGR_SHIFT;
+	return mmio_read_32(base + GICD_ICFGR + (n << 2));

WARNING: Missing a blank line after declarations
#2299: FILE: drivers/arm/gic/common/gic_common.c:135:
+	unsigned n = id >> NSACR_SHIFT;
+	return mmio_read_32(base + GICD_NSACR + (n << 2));

WARNING: Missing a blank line after declarations
#2312: FILE: drivers/arm/gic/common/gic_common.c:148:
+	unsigned n = id >> IGROUPR_SHIFT;
+	mmio_write_32(base + GICD_IGROUPR + (n << 2), val);

WARNING: Missing a blank line after declarations
#2322: FILE: drivers/arm/gic/common/gic_common.c:158:
+	unsigned n = id >> ISENABLER_SHIFT;
+	mmio_write_32(base + GICD_ISENABLER + (n << 2), val);

WARNING: Missing a blank line after declarations
#2332: FILE: drivers/arm/gic/common/gic_common.c:168:
+	unsigned n = id >> ICENABLER_SHIFT;
+	mmio_write_32(base + GICD_ICENABLER + (n << 2), val);

WARNING: Missing a blank line after declarations
#2342: FILE: drivers/arm/gic/common/gic_common.c:178:
+	unsigned n = id >> ISPENDR_SHIFT;
+	mmio_write_32(base + GICD_ISPENDR + (n << 2), val);

WARNING: Missing a blank line after declarations
#2352: FILE: drivers/arm/gic/common/gic_common.c:188:
+	unsigned n = id >> ICPENDR_SHIFT;
+	mmio_write_32(base + GICD_ICPENDR + (n << 2), val);

WARNING: Missing a blank line after declarations
#2362: FILE: drivers/arm/gic/common/gic_common.c:198:
+	unsigned n = id >> ISACTIVER_SHIFT;
+	mmio_write_32(base + GICD_ISACTIVER + (n << 2), val);

WARNING: Missing a blank line after declarations
#2372: FILE: drivers/arm/gic/common/gic_common.c:208:
+	unsigned n = id >> ICACTIVER_SHIFT;
+	mmio_write_32(base + GICD_ICACTIVER + (n << 2), val);

WARNING: Missing a blank line after declarations
#2382: FILE: drivers/arm/gic/common/gic_common.c:218:
+	unsigned n = id >> IPRIORITYR_SHIFT;
+	mmio_write_32(base + GICD_IPRIORITYR + (n << 2), val);

WARNING: Missing a blank line after declarations
#2392: FILE: drivers/arm/gic/common/gic_common.c:228:
+	unsigned n = id >> ICFGR_SHIFT;
+	mmio_write_32(base + GICD_ICFGR + (n << 2), val);

WARNING: Missing a blank line after declarations
#2402: FILE: drivers/arm/gic/common/gic_common.c:238:
+	unsigned n = id >> NSACR_SHIFT;
+	mmio_write_32(base + GICD_NSACR + (n << 2), val);

WARNING: Missing a blank line after declarations
#2523: FILE: drivers/arm/gic/v3/gicv3_helpers.c:45:
+	unsigned n = id >> IGRPMODR_SHIFT;
+	return mmio_read_32(base + GICD_IGRPMODR + (n << 2));

WARNING: Missing a blank line after declarations
#2533: FILE: drivers/arm/gic/v3/gicv3_helpers.c:55:
+	unsigned n = id >> IGRPMODR_SHIFT;
+	mmio_write_32(base + GICD_IGRPMODR + (n << 2), val);

WARNING: Missing a blank line after declarations
#2579: FILE: drivers/arm/gic/v3/gicv3_helpers.c:101:
+	unsigned n = id >> IPRIORITYR_SHIFT;
+	return mmio_read_32(base + GICR_IPRIORITYR + (n << 2));

WARNING: Missing a blank line after declarations
#2589: FILE: drivers/arm/gic/v3/gicv3_helpers.c:111:
+	unsigned n = id >> IPRIORITYR_SHIFT;
+	mmio_write_32(base + GICR_IPRIORITYR + (n << 2), val);

WARNING: quoted string split across lines
#3007: FILE: drivers/arm/gic/v3/gicv3_main.c:108:
+	INFO("GICv3 %s legacy support detected."
+			" ARM GICV3 driver initialized in EL3\n",

WARNING: line over 80 characters
#3035: FILE: drivers/arm/gic/v3/gicv3_main.c:136:
+	/* Set the ARE_S and ARE_NS bit now that interrupts have been disabled */

WARNING: line over 80 characters
#3415: FILE: drivers/arm/gic/v3/gicv3_private.h:129:
+static inline unsigned long long gicd_read_irouter(uintptr_t base, unsigned int id)

WARNING: line over 80 characters
#3899: FILE: include/drivers/arm/gicv3.h:196:
+ * GICv3 IP. It is used by the platform port to specify these attributes in order

WARNING: do not add new typedefs
#3942: FILE: include/drivers/arm/gicv3.h:239:
+typedef struct gicv3_driver_data {

WARNING: Do not use whitespace before Signed-off-by:
#4051: 
    Signed-off-by: Varun Wadekar <vwadekar@nvidia.com>

WARNING: externs should be avoided in .c files
#4206: FILE: plat/nvidia/tegra/common/tegra_pm.c:47:
+extern uint64_t tegra_sec_entry_point;

WARNING: externs should be avoided in .c files
#4581: FILE: plat/nvidia/tegra/common/tegra_topology.c:35:
+extern const unsigned char tegra_power_domain_tree_desc[];

ERROR: space required after that ',' (ctx:VxV)
#4957: FILE: plat/nvidia/tegra/soc/t210/plat_psci_handlers.c:134:
+	ERROR("%s: unsupported state id (%d)\n", __func__,state_id);
 	                                                 ^

WARNING: Do not use whitespace before Signed-off-by:
#5125: 
    Signed-off-by: Varun Wadekar <vwadekar@nvidia.com>

WARNING: Duplicate signature
#5125: 
    Signed-off-by: Varun Wadekar <vwadekar@nvidia.com>

total: 1 errors, 43 warnings, 4635 lines checked

NOTE: Ignored message types: COMPLEX_MACRO GERRIT_CHANGE_ID GIT_COMMIT_ID

Your patch has style problems, please review.

If any of these errors are false positives, please report
them to the maintainer, see CHECKPATCH in MAINTAINERS.
```

**Comment by danh-arm** [comment]
There's also a build error in our CI:
```
Build options: CROSS_COMPILE=aarch64-linux-gnu- V=1 DEBUG=1 PLAT=tegra TARGET_SOC=t132 SPD=tlkd
```

```
 CC      plat/common/aarch64/plat_psci_common.c
aarch64-linux-gnu-gcc -g -nostdinc -ffreestanding -Wall -Werror -Wmissing-include-dirs -mgeneral-regs-only -mstrict-align -std=c99 -c -Os -DDEBUG=1 -DCRASH_REPORTING=1 -DASM_ASSERTION=1 -DTEGRA_BOOT_UART_BASE=0x70006300 -DTZDRAM_BASE=0xF5C00000 -DPLATFORM_CLUSTER_COUNT=1 -DPLATFORM_MAX_CPUS_PER_CLUSTER=2 -DSKIP_A57_L1_FLUSH_PWR_DWN=0 -DERRATA_A53_826319=0 -DERRATA_A53_836870=0 -DERRATA_A57_806969=0 -DERRATA_A57_813420=0 -DPLAT_tegra -DNS_TIMER_SWITCH=0 -DRESET_TO_BL31=0 -DCTX_INCLUDE_FPREGS=0 -DARM_GIC_ARCH=2 -DARM_CCI_PRODUCT_ID=400 -DASM_ASSERTION=1 -DLOG_LEVEL=40 -DUSE_COHERENT_MEM=0 -DTRUSTED_BOARD_BOOT=0 -DPROGRAMMABLE_RESET_ADDRESS=0 -DCOLD_BOOT_SINGLE_CPU=0 -DPSCI_EXTENDED_STATE_ID=0 -DERROR_DEPRECATED=0 -DENABLE_PLAT_COMPAT=0 -DSPIN_ON_BL1_EXIT=0 -DCRASH_REPORTING=1 -Iinclude/bl31 -Iinclude/bl31/services -Iinclude/common -Iinclude/drivers -Iinclude/drivers/arm -Iinclude/drivers/auth -Iinclude/drivers/io -Iinclude/drivers/ti/uart -Iinclude/lib -Iinclude/lib/aarch64 -Iinclude/lib/cpus/aarch64 -Iinclude/plat/common -Iinclude/stdlib -Iinclude/stdlib/sys -Iplat/nvidia/tegra/include/drivers -Iplat/nvidia/tegra/include -Iplat/nvidia/tegra/include/t132 -Iinclude/bl32/payloads -ffunction-sections -fdata-sections -pedantic -Wno-error=deprecated-declarations -DIMAGE_BL31 -c plat/common/aarch64/plat_psci_common.c -o build/tegra/t132/debug/bl31/plat_psci_common.o
In file included from include/lib/bakery_lock.h:34:0,
                 from include/bl31/services/psci.h:34,
                 from include/plat/common/platform.h:34,
                 from plat/common/aarch64/plat_psci_common.c:33:
plat/common/aarch64/plat_psci_common.c: In function 'plat_get_target_pwr_state':
plat/nvidia/tegra/include/platform_def.h:61:30: error: 'PLAT_SYS_SUSPEND_STATE_ID' undeclared (first use in this function)
 #define PLAT_MAX_OFF_STATE  (PLAT_SYS_SUSPEND_STATE_ID + 1)
                              ^
plat/common/aarch64/plat_psci_common.c:52:30: note: in expansion of macro 'PLAT_MAX_OFF_STATE'
  plat_local_state_t target = PLAT_MAX_OFF_STATE, temp;
                              ^
plat/nvidia/tegra/include/platform_def.h:61:30: note: each undeclared identifier is reported only once for each function it appears in
 #define PLAT_MAX_OFF_STATE  (PLAT_SYS_SUSPEND_STATE_ID + 1)
                              ^
plat/common/aarch64/plat_psci_common.c:52:30: note: in expansion of macro 'PLAT_MAX_OFF_STATE'
  plat_local_state_t target = PLAT_MAX_OFF_STATE, temp;
                              ^
make: *** [build/tegra/t132/debug/bl31/plat_psci_common.o] Error 1
Build failed with code 2
```

**Comment by vwadekar** [comment]
New PR - #450

**Pull request closed without merging**
