### PR TITLE
update the interrupt diagrams

### PR DESCRIPTION
**Pull request by geesun**
The sec-int-handling.png was mismatched with the code, we should change TSP_HANDLED_S_EL1_FIQ to TSP_HANDLED_S_EL1_INTR in sec-int-handling.png. 
   
   - Redraw the interrupt diagrams with dia tool
   - Change TSP_HANDLED_S_EL1_FIQ to TSP_HANDLED_S_EL1_INTR in sec-int-handling.png
   - Use the makefile generate the image to avoid unnessary generate
   - Add dia source code

### CODE REVIEW

**Comment by antonio-nino-diaz-arm** [comment]
Why is the resolution of the new png files so small compared to the old ones?

**Comment by geesun** [comment]
I update the script to generate the image the same size as before.

**Comment by danh-arm** [comment]
jenkins: add to whitelist

**Comment by danh-arm** [comment]
jenkins: test this please

**Pull request merged**
