### PR TITLE
Update Intel Stratix10 DDR calibration fixes and add simple MBR partition support

### PR DESCRIPTION
**Pull request by thloh85-intel**
This fixes an issue with intel socfpga's ECC DDR calibration, and adds a simple MBR partition support.
Do I need to split this up into two pull requests?

### CODE REVIEW

**Comment by antonio-nino-diaz-arm** [comment]
That's up to you. If you want the patch for your platform to be merged sooner, you can probably split them until @hzhuang1 has time to take a look at the other patch. If you don't mind waiting, you can keep them together.

IP Review +1

**Comment by antonio-nino-diaz-arm** [comment]
jenkins: test this please

**Comment by antonio-nino-diaz-arm** [comment]
This has checkpatch errors:
```
[*] Checking style of '60c1467dbdf44fc11de2a4994e188fc70872fb58'

drivers/partition/partition.c:108: ERROR: open brace '{' following function definitions go on the next line
+static int load_mbr_entry(uintptr_t image_handle, mbr_entry_t *mbr_entry,
+			int part_number) {

drivers/partition/partition.c:141: ERROR: open brace '{' following function definitions go on the next line
+static int load_mbr_entries(uintptr_t image_handle) {
```
Also, the following config fails to build:
```
AARCH32_SP=sp_min
ARCH=aarch32
ARM_ARCH_MAJOR=7
CROSS_COMPILE=arm-linux-gnueabihf-
PLAT=stm32mp1
```
With this output:
```
arm-linux-gnueabihf-gcc -g -DDEBUG=1 -DENABLE_BACKTRACE=0 -DSTM32_TF_A_COPIES=2 -DPLAT_PARTITION_MAX_ENTRIES=3 -DXLAT_TABLES_LIB_V2=1 -DARMV7_SUPPORTS_LARGE_PAGE_ADDRESSING -DARMV7_SUPPORTS_VIRTUALIZATION -DARMV7_SUPPORTS_GENERIC_TIMER -DSKIP_A57_L1_FLUSH_PWR_DWN=0 -DA53_DISABLE_NON_TEMPORAL_HINT=1 -DA57_DISABLE_NON_TEMPORAL_HINT=1 -DWORKAROUND_CVE_2017_5715=0 -DWORKAROUND_CVE_2018_3639=1 -DDYNAMIC_WORKAROUND_CVE_2018_3639=0 -DERRATA_A53_826319=0 -DERRATA_A53_835769=0 -DERRATA_A53_836870=0 -DERRATA_A53_843419=0 -DERRATA_A53_855873=0 -DERRATA_A57_806969=0 -DERRATA_A57_813419=0 -DERRATA_A57_813420=0 -DERRATA_A57_826974=0 -DERRATA_A57_826977=0 -DERRATA_A57_828024=0 -DERRATA_A57_829520=0 -DERRATA_A57_833471=0 -DERRATA_A57_859972=0 -DERRATA_A72_859971=0 -DERRATA_ARES_1043202=1 -DERRATA_DSU_936184=0 -DRESET_TO_SP_MIN=0 -DSP_MIN_WITH_SECURE_FIQ=1 -DSTACK_PROTECTOR_ENABLED=0 -DARM_ARCH_MAJOR=7 -DARM_ARCH_MINOR=0 -DCOLD_BOOT_SINGLE_CPU=0 -DCTX_INCLUDE_AARCH32_REGS=1 -DCTX_INCLUDE_FPREGS=0 -DEL3_EXCEPTION_HANDLING=0 -DENABLE_AMU=0 -DENABLE_ASSERTIONS=1 -DENABLE_MPAM_FOR_LOWER_ELS=0 -DENABLE_PIE=0 -DENABLE_PMF=0 -DENABLE_PSCI_STAT=0 -DENABLE_RUNTIME_INSTRUMENTATION=0 -DENABLE_SPE_FOR_LOWER_ELS=0 -DENABLE_SPM=0 -DENABLE_SVE_FOR_NS=0 -DERROR_DEPRECATED=0 -DFAULT_INJECTION_SUPPORT=0 -DGICV2_G0_FOR_EL3=0 -DHANDLE_EA_EL3_FIRST=0 -DHW_ASSISTED_COHERENCY=0 -DLOG_LEVEL=40 -DMULTI_CONSOLE_API=1 -DNS_TIMER_SWITCH=0 -DPL011_GENERIC_UART=0 -DPLAT_stm32mp1 -DPROGRAMMABLE_RESET_ADDRESS=0 -DPSCI_EXTENDED_STATE_ID=0 -DRAS_EXTENSION=0 -DRESET_TO_BL31=0 -DSEPARATE_CODE_AND_RODATA=0 -DRECLAIM_INIT_CODE=0 -DSPD_none -DSPIN_ON_BL1_EXIT=0 -DSPM_MM=1 -DTRUSTED_BOARD_BOOT=0 -DUSE_COHERENT_MEM=0 -DUSE_ROMLIB=0 -DUSE_TBBR_DEFS=1 -DWARMBOOT_ENABLE_DCACHE_EARLY=0 -DBL2_AT_EL3=1 -DBL2_IN_XIP_MEM=0 -DAARCH32 -Iinclude -Iinclude/arch/aarch32 -Iinclude/lib/cpus/aarch32 -Iinclude/lib/el3_runtime/aarch32 -Iplat/st/stm32mp1/include/  -Iinclude/bl1 -Iinclude/bl2 -Iinclude/bl2u -Iinclude/bl31 -Iinclude/drivers -Iinclude/drivers/arm -Iinclude/drivers/auth -Iinclude/drivers/io -Iinclude/drivers/ti/uart -Iinclude/lib -Iinclude/lib/cpus -Iinclude/lib/el3_runtime -Iinclude/lib/extensions -Iinclude/lib/pmf -Iinclude/lib/psci -Iinclude/lib/xlat_tables -Iinclude/plat/common -Iinclude/services -Iinclude/tools_share -Iinclude/lib/libfdt -Iinclude/bl32/sp_min -Iinclude/lib/libc -Iinclude/lib/libc/aarch32   -nostdinc -Wmissing-include-dirs -Werror  -Wno-error=deprecated-declarations -Wno-error=cpp -mcpu=cortex-a7 -mfpu=neon -mthumb -mno-unaligned-access -ffreestanding -fno-builtin -Wall -std=gnu99 -Os -ffunction-sections -fdata-sections   -DIMAGE_BL2 -Wp,-MD,./build/stm32mp1/debug/bl2/partition.d -MT build/stm32mp1/debug/bl2/partition.o -MP -c drivers/partition/partition.c -o build/stm32mp1/debug/bl2/partition.o
drivers/partition/partition.c: In function 'load_partition_table':
drivers/partition/partition.c:229:1: error: label 'exit' defined but not used [-Werror=unused-label]
 exit:
 ^~~~
cc1: all warnings being treated as errors
Makefile:726: recipe for target 'build/stm32mp1/debug/bl2/partition.o' failed
make: *** [build/stm32mp1/debug/bl2/partition.o] Error 1
```
Also, stratix10 fails to build. Same output.

**Comment by Yann-lms** [comment]
Thanks @antonio-nino-diaz-arm for spotting this error (as well as the one in the other PR) in STM32MP1.
Removing the `exit:` label should correct the issue

**Comment by hzhuang1** [comment]
@antonio-nino-diaz-arm Acked.

**Comment by thloh85-intel** [comment]
Sorry I didn't run checkpatch in the last commit. New patch up. Thanks to all reviewers.

**Comment by antonio-nino-diaz-arm** [comment]
jenkins: test this please

**Comment by thloh85-intel** [comment]
Fixing a few more bugs. I'll update this once test is completed. Thanks!

**Pull request closed without merging**
