### PR TITLE
MT8183: support suspend/resume feature

### PR DESCRIPTION
**Pull request by kennyliang-mtk**
It is based on and related to PR #1635 .
Because it is a big feature, make it another PR to review.

Add the following to support suspend/resume
- Add mcusys dcm setting
- Add rtc power-off sequence
- Init spm and load spm firmware to support suspend/resume
- Add needed cirq and gic driver for spm

### CODE REVIEW

**Comment by mtk09422** [comment]
I am OK with this patch.

**Comment by kennyliang-mtk** [comment]
Could one of the admins help verify this patch?
Thanks.

**Comment by antonio-nino-diaz-arm** [comment]
This patch looks good to me, but it depends on https://github.com/ARM-software/arm-trusted-firmware/pull/1635. I'll say the same thing I've said in the other PR, just build with ``ERROR_DEPRECATED=1`` and fix the issues that appear. Also, it would be nice to have a short document in ``docs/plat/`` explaining how to build the firmware so that we can add it to the CI.

**Comment by antonio-nino-diaz-arm** [comment]
As part of the migration to trustedfirmware.org https://github.com/ARM-software/tf-issues/issues/681 we have switched the main development repository to Gerrit (https://review.trustedfirmware.org/). It is unfortunate that the switch has happened while your PR was being reviewed, but we don't intend to merge more patches through GitHub to avoid confusion.

Could you please follow the instructions in https://github.com/ARM-software/arm-trusted-firmware/blob/master/contributing.rst to continue with the review? We're sorry for the inconvenience.

**Comment by sandrine-bailleux-arm** [comment]
In addition to the [contribution guidelines](https://github.com/ARM-software/arm-trusted-firmware/blob/master/contributing.rst), the following [Getting starting guide](https://developer.trustedfirmware.org/w/tf_a/gerrit-getting-started/) might help in this process.

**Pull request closed without merging**
