### PR TITLE
Run bl32 on tegra v3

### PR DESCRIPTION
**Pull request by vwadekar**
Load and boot a BL32 image on Tegra SoCs during boot. Update the documentation to include tlkd as part of the bl31.bin as well.

### CODE REVIEW

**Comment by vwadekar** [comment]
Fixed comments from #313

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by achingupta** [comment]
@jenswi-linaro @jbech-linaro FYI. This PR moves the SPD documentation to from the `docs` folder to the `docs\spd` folder. In case you need to update some internal instructions.

**Comment by achingupta** [comment]
test this please

**Comment by jbech-linaro** [comment]
@achingupta thanks for the update, I checked our documentation and I couldn't find any direct link to optee-dispatcher.md. Anyhow, thanks!

**Comment by vwadekar** [comment]
Achin, does this look good to go?

**Comment by vwadekar** [comment]
Thanks a lot!

**Comment by vwadekar** [comment]
Achin, when would these changes appear in the master branch?

**Comment by achingupta** [comment]
Done!

**Comment by vwadekar** [comment]
Thanks

**Pull request merged**
