### PR TITLE
rpi3: enlarge SEC_DRAM0_SIZE for optee_test to pass

### PR DESCRIPTION
**Pull request by grandpaul**
Running optee_test failed because SEC_DRAM0_SIZE is too small. Previous
is 2 MB. We enlarge it to 11 MB for passing the test. Also we reduce
the NS_DRAM0_SIZE from 13MB to 4MB so that the whole section is still
fit in 16MB.

### CODE REVIEW

**Comment by antonio-nino-diaz-arm** [comment]
IP Review +1

**Comment by antonio-nino-diaz-arm** [comment]
Actually, I think it's better if you squash the two patches.

**Comment by igoropaniuk** [comment]
@grandpaul please, don't forget to update https://github.com/OP-TEE/optee_os/pull/2394 accordingly. Thanks!

**Comment by dp-arm** [comment]
jenkins: test this please

**Comment by antonio-nino-diaz-arm** [comment]
The failures are just infrastructure issues, and the build configs that failed to run are for Juno, so this PR is fine.

**Pull request merged**
