### PR TITLE
plat/arm: allow RESET_TO_BL31 for CSS-based platforms

### PR DESCRIPTION
**Pull request by deepan02**
Currently RESET_TO_BL31 is not allowed for any of the CSS platforms.
A compilation error is generated when RESET_TO_BL31=1.

This patch removes the condition check from generic css_common.mk and
adds the same check to the platform.mk files of the CSS platforms that
do not support RESET_TO_BL31.

Change-Id: I32a90fce43cb0c6f4d33589653a0fd6a7ecc9577
Signed-off-by: Deepak Pandey <Deepak.Pandey@arm.com>

### CODE REVIEW

**Comment by jeenu-arm** [comment]
jenkins: test this please

**Comment by dp-arm** [comment]
jenkins: test this please

**Comment by dp-arm** [comment]
jenkins: test this please

**Comment by soby-mathew** [comment]
jenkins: test this please

**Comment by soby-mathew** [comment]
@deepan02 , Could you address the review comment from Nariman ?

**Comment by deepan02** [comment]
Ignore the push ,some gone wrong here !

**Comment by deepan02** [comment]
closing this as new pull request would be created

**Pull request closed without merging**
