### PR TITLE
Spm

### PR DESCRIPTION
**Pull request by mtk09422**
Update SPM/DCM related code for power control logic

previous PR: https://github.com/ARM-software/arm-trusted-firmware/pull/437

### CODE REVIEW

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by danh-arm** [comment]
test this please

**Comment by danh-arm** [comment]
Contains same build error as #447

**Comment by jimmyh-mtk** [comment]
fix build error in #447, could you trigger the test build again? Thanks.

**Comment by danh-arm** [comment]
retest this please

**Comment by WeiyiLu** [comment]
Thanks for the information, it's indeed unnecessary to trace the on_pending state. We will submit a new commit for related code removal.

**Comment by jimmyh-mtk** [comment]
We are currently discussing with Julius (@Google) on whether the regulator control code should be in BL31 or not. The mmu patch is needed for that. If it turns out that we shouldn't put those code in BL31, we then will need to update some code for this. We will not update the patches (mmu and regulator control related code) until we have a conclusion on this topic.

**Pull request closed without merging**
