### PR TITLE
Remove deprecated interfaces for all platforms

### PR DESCRIPTION
**Pull request by antonio-nino-diaz-arm**
This pull request removes all deprecated interfaces of the codebase as it was warned in https://github.com/ARM-software/tf-issues/issues/613.

This is a quite invasive change and most platforms break after applying the first commits. Most changes were quite trivial so they were easy to do for us. I've tried to preserve compatibility with all platforms, but we have no way to test them locally so we need all maintainers to test that the changes are correct.

Unfortunately, the changes needed for Marvell (@kostapr), Nvidia (@vwadekar) and MediaTek mt6795 (@mtk09422) aren't trivial so I haven't been able to fully migrate the platforms. @kostapr, I know I didn't mention this specific problem in https://github.com/ARM-software/tf-issues/issues/613, sorry about that.

Could you please reply by Tuesday next week (2018-10-02)?

Also, please reply with a ``Tested-by: Name <email>`` tag so that I can add them to the patches.

### CODE REVIEW

**Comment by b49020** [comment]
For plat/socionext/synquacer/, `Tested-by: Sumit Garg <sumit.garg@linaro.org>`

**Comment by glneo** [comment]
For TI platforms:
```
Acked-by: Andrew F. Davis <afd@ti.com>
```

**Comment by Andre-ARM** [comment]
For the Allwinner platform:
Tested by: Andre Przywara <andre.przywara@arm.com>
(boot tested on each of H5, A64, H6)

**Comment by jenswi-linaro** [comment]
For qemu: `Tested-by: Jens Wiklander <jens.wiklander@linaro.org>` with the patch below applied:
```patch
diff --git a/plat/qemu/qemu_bl1_setup.c b/plat/qemu/qemu_bl1_setup.c
index 4a5d74a795db..fd53495a6420 100644
--- a/plat/qemu/qemu_bl1_setup.c
+++ b/plat/qemu/qemu_bl1_setup.c
@@ -39,7 +39,7 @@ void bl1_early_platform_setup(void)
  * does not do anything platform specific.
  *****************************************************************************/
 #ifdef AARCH32
-#define QEMU_CONFIGURE_BL1_MMU(...)	qemu_configure_mmu_secure(__VA_ARGS__)
+#define QEMU_CONFIGURE_BL1_MMU(...)	qemu_configure_mmu_svc_mon(__VA_ARGS__)
 #else
 #define QEMU_CONFIGURE_BL1_MMU(...)	qemu_configure_mmu_el3(__VA_ARGS__)
 #endif
diff --git a/plat/qemu/qemu_bl2_setup.c b/plat/qemu/qemu_bl2_setup.c
index 59ce7ef7b37d..d76621d8fb94 100644
--- a/plat/qemu/qemu_bl2_setup.c
+++ b/plat/qemu/qemu_bl2_setup.c
@@ -77,7 +77,7 @@ void bl2_platform_setup(void)
 }
 
 #ifdef AARCH32
-#define QEMU_CONFIGURE_BL2_MMU(...)	qemu_configure_mmu_secure(__VA_ARGS__)
+#define QEMU_CONFIGURE_BL2_MMU(...)	qemu_configure_mmu_svc_mon(__VA_ARGS__)
 #else
 #define QEMU_CONFIGURE_BL2_MMU(...)	qemu_configure_mmu_el1(__VA_ARGS__)
 #endif
diff --git a/plat/qemu/qemu_common.c b/plat/qemu/qemu_common.c
index 2d4198b7d248..376ff2f1151e 100644
--- a/plat/qemu/qemu_common.c
+++ b/plat/qemu/qemu_common.c
@@ -131,7 +131,7 @@ static const mmap_region_t plat_qemu_mmap[] = {
 
 /* Define EL1 and EL3 variants of the function initialising the MMU */
 #ifdef AARCH32
-DEFINE_CONFIGURE_MMU_EL(secure)
+DEFINE_CONFIGURE_MMU_EL(svc_mon)
 #else
 DEFINE_CONFIGURE_MMU_EL(el1)
 DEFINE_CONFIGURE_MMU_EL(el3)
diff --git a/plat/qemu/qemu_private.h b/plat/qemu/qemu_private.h
index 0fb7cd5fd220..88b93da827a4 100644
--- a/plat/qemu/qemu_private.h
+++ b/plat/qemu/qemu_private.h
@@ -11,7 +11,7 @@
 
 #include "../../bl1/bl1_private.h"
 
-void qemu_configure_mmu_secure(unsigned long total_base,
+void qemu_configure_mmu_svc_mon(unsigned long total_base,
 			unsigned long total_size,
 			unsigned long code_start, unsigned long code_limit,
 			unsigned long ro_start, unsigned long ro_limit,
```

**Comment by hzhuang1** [comment]
For hikey-* platform

Tested-by: Haojian Zhuang <haojian.zhuang@linaro.org>

**Comment by antonio-nino-diaz-arm** [comment]
@hzhuang1, do you mean that you have tested hikey960 as well?

Thanks, @jenswi-linaro. I've just realized that we don't build the QEMU port in 32-bit in our CI, and the build with SP_MIN is broken. I can still build it with OP-TEE, though.

**Comment by hzhuang1** [comment]
Yes

**Comment by kostapr** [comment]
I will be able to work on the required changes when back to office in October 2nd. The Israel team is on long holidays period right now.

**Comment by sivadur** [comment]
For Xilinx ZynqMP

Tested-by: Siva Durga Prasad Paladugu <siva.durga.paladugu@xilinx.com>

**Comment by antonio-nino-diaz-arm** [comment]
@kostapr Are you ok with us merging this patch in the meantime? The changes are quite trivial, and you will have to test them when you migrate to using LOAD_IMAGE_V2 structs.

**Comment by shawnguo2** [comment]
@antonio-nino-diaz-arm Poplar gets broken like below.
```
INFO:    BL1: 0x2016000 - 0x201c000 [size = 24576]
NOTICE:  Booting Trusted Firmware
NOTICE:  BL1: v1.6(debug):v1.6-39-g97c87c00e9fd
NOTICE:  BL1: Built : 15:17:12, Sep 28 2018
INFO:    BL1: RAM 0x2016000 - 0x201c000
INFO:    BL1: cortex_a53: CPU workaround for 855873 was applied
INFO:    BL1: initializing emmc
INFO:    BL1: Loading BL2
INFO:    Using eMMC
INFO:    Using FIP
INFO:    Loading image id=1 at address 0x201e000
INFO:    Image id=1 loaded: 0x201e000 - 0x20243b8
ASSERT: bl1/bl1_main.c:44
BACKTRACE: START: assert
0: EL3: 0x201104c
1: EL3: 0x20122f0
2: EL3: 0x201056c
3: EL3: 0x2010cac
4: EL3: 0x20106f8
5: EL3: 0x200e090
BACKTRACE: END: assert
```

**Comment by antonio-nino-diaz-arm** [comment]
@shawnguo2, can you modify the assert in ``bl1/bl1_main.c:44`` to ``assert(BL1_RW_BASE >= bl1_mem_layout->total_base);`` and tell me if it works?

**Comment by antonio-nino-diaz-arm** [comment]
OK, @shawnguo2, you have a bigger problem than this assert. The assert is fine, the problem is that the default implementation of ``bl1_plat_handle_post_image_load()`` expects BL1_RW to be at the end of your protected memory. Also, your ``bl2_mem_layout`` is overwriting variables in BL1_RW.

Could you check this branch https://github.com/antonio-nino-diaz-arm/arm-trusted-firmware/tree/an/deprecated-poplar ?

**Comment by antonio-nino-diaz-arm** [comment]
@masahir0y I know, and my intention is to reverse the order of the patches before the final merge. However, in GitHub if you update the PR all the new patches are moved to the end of the conversation and it gets a bit confusing with so many patches.

**Comment by antonio-nino-diaz-arm** [comment]
Ok, @masahir0y , I've done a small test and I think it's too much effort for very little gain. For example, for ``LOAD_IMAGE_V2``. By default all platforms use ``LOAD_IMAGE_V2=1`` and each platform's makefile overrides it to 1 if needed.

In order to preserve bisectability I need to do the changes like this:

1. Update platform A to use LOAD_IMAGE_V2=1.
2. Update platform B to use LOAD_IMAGE_V2=1.
2. Remove LOAD_IMAGE_V1 and remove lines ``LOAD_IMAGE_V2=1`` from both makefiles.

In the end, this means that for the maintainers to see what has changed they have to go through a patch that only applies to their platforms and another one that removes the API and only removes one line from their makefiles. It's easier to review if all the changes related to a platform are limited to a patch.

It's also easier to review the patches that remove the deprecated APIs if we don't add a lot of small changes to a lot of platform makefiles.

Another reason is that bisectability would mean that some platforms wouldn't have any commit specific for them (allwinner, warp7). We'd like to keep track of what works and what doesn't because there may be unexpected breaks like in poplar. This way I can add a ``Reviewed-by`` tag to each individual platform and it's easy to see what has been tested by whom. We've done the migration of all platforms blindly, we don't have any of them to test with, so keeping track of which migrations have been tested is very important to us.

Normally we try to not break builds at patch level (internally we test each patch in Gerrit for build problems). However, we only really enforce that at PR level. I agree that git bisect is a valuable tool, but in this case I think it is obvious that any problem has been introduced because of the removal of the deprecated interfaces and that's all most platform maintainers need to know (most changes are quite trivial, so the big change in your platform is most likely the problematic one).

**Comment by shawnguo2** [comment]
> Could you check this branch https://github.com/antonio-nino-diaz-arm/arm-trusted-firmware/tree/an/deprecated-poplar ?

Yes, this branch works!  Thanks for fixing Poplar, @antonio-nino-diaz-arm

**Comment by antonio-nino-diaz-arm** [comment]
Ok, great @shawnguo2. I've squashed that patch with the previous one and updated this PR.

**Comment by kostapr** [comment]
> @kostapr Are you ok with us merging this patch in the meantime? The changes are quite trivial, and you will have to test them anyway when you migrate to using LOAD_IMAGE_V2 structs.
@antonio-nino-diaz-arm 
Yes, I do not want to block your work. Hope nobody will complain about Marvell platform here till I made the required changes.

**Comment by soby-mathew** [comment]
@vwadekar, @mtk09422, @qoriq-open-source, @Anson-Huang, @TonyXie06,  @rockchip-linux, 
We will be merging this PR tomorrow. Please let us know if you have any feedback before that.

**Pull request merged**
