### PR TITLE
drivers: partition: Add simple MBR partition entries support

### PR DESCRIPTION
**Pull request by thloh85-intel**
This is to add simple MBR partition entry support. This will read all four
MBR partition into the partition list, and the partition type will be saved
in the list.name[0] entry.

Signed-off-by: Loh Tien Hock <tien.hock.loh@intel.com>

### CODE REVIEW

**Comment by hzhuang1** [comment]
Acked

**Comment by antonio-nino-diaz-arm** [comment]
IP Review +1

**Comment by antonio-nino-diaz-arm** [comment]
jenkins: test this please

**Comment by antonio-nino-diaz-arm** [comment]
The CI failure is due to infrastructure issues with the Coverity server.

**Pull request merged**
