### PR TITLE
Patches for 8173 crbook 

### PR DESCRIPTION
**Pull request by freedomtan**
Patches for PR  https://github.com/ARM-software/arm-trusted-firmware/pull/737 updated

Patches for MT8173:
1. enable ENABLE_PLAT_COMPAT=1
2. add PSCI_EXTENDED_STATE_ID supported
3. remove use of some old / deprecated APIs

What works,
1. ENABLE_PLAT_COMPAT=1
2. ENABLE_PLAT_COMPAT=0
3. ENABLE_PLAT_COMPAT=0 PSCI_EXTENDED_STATE_ID=1
4. ERROR_DEPRECATED=[01] for 1., 2., and 3.

### CODE REVIEW

**Comment by danh-arm** [comment]
jenkins: test this please

**Comment by danh-arm** [comment]
Hi @freedomtan. One of the commits in this PR just changed while I was reviewing it. Please let me know if there are further changes to come otherwise I will merge.

Hi @mtk09422. I intend to merge this today FYI since you already approved the fundamental changes in #737.

**Comment by danh-arm** [comment]
This PR failed the checkpatch test. At least the errors below need fixing (preferably the warnings too where possible):

```
plat/mediatek/mt8173/include/mt8173_def.h:138: WARNING: Block comments use * on subsequent lines
+/* Local power state for OFF/power-down. Valid for CPU and cluster power
+   domains */

plat/mediatek/mt8173/include/mt8173_def.h:138: WARNING: Block comments use a trailing */ on a separate line
+   domains */

plat/mediatek/mt8173/plat_pm.c:290: WARNING: Missing a blank line after declarations
+	unsigned int scr;
+	scr = read_scr_el3();

plat/mediatek/mt8173/plat_pm.c:496: WARNING: braces {} are not necessary for single statement blocks
+		if (MTK_CLUSTER_PWR_STATE(state) == MTK_LOCAL_STATE_OFF) {
+			spm_mcdi_prepare_for_off_state(mpidr, MTK_PWR_LVL1);
+		}

plat/mediatek/mt8173/plat_pm.c:638: WARNING: braces {} are not necessary for single statement blocks
+		if (MTK_CLUSTER_PWR_STATE(state) == MTK_LOCAL_STATE_OFF) {
+			spm_mcdi_finish_for_on_state(mpidr, MTK_PWR_LVL1);
+		}

plat/mediatek/mt8173/plat_pm.c:783: WARNING: line over 80 characters
+int plat_setup_psci_ops(uintptr_t sec_entrypoint, const plat_psci_ops_t **psci_ops)

plat/mediatek/mt8173/plat_topology.c:112: WARNING: Duplicate signature
Signed-off-by: Koan-Sin Tan <koansin.tan@gmail.com>

plat/mediatek/mt8173/include/mt8173_def.h:154: WARNING: line over 80 characters
+		(((lvl0_state) << PSTATE_ID_SHIFT) | ((type) << PSTATE_TYPE_SHIFT))

plat/mediatek/mt8173/include/mt8173_def.h:169: WARNING: line over 80 characters
+#define mtk_make_pwrstate_lvl2(lvl2_state, lvl1_state, lvl0_state, pwr_lvl, type) \

plat/mediatek/mt8173/plat_pm.c:799: WARNING: Duplicate signature
Signed-off-by: Koan-Sin Tan <koansin.tan@gmail.com>

plat/mediatek/mt8173/include/platform_def.h:142: ERROR: code indent should use tabs where possible
+                                MT_IRQ_SEC_SGI_1,      \$

plat/mediatek/mt8173/include/platform_def.h:142: WARNING: please, no spaces at the start of a line
+                                MT_IRQ_SEC_SGI_1,      \$

plat/mediatek/mt8173/include/platform_def.h:143: ERROR: code indent should use tabs where possible
+                                MT_IRQ_SEC_SGI_2,      \$

plat/mediatek/mt8173/include/platform_def.h:143: WARNING: please, no spaces at the start of a line
+                                MT_IRQ_SEC_SGI_2,      \$

plat/mediatek/mt8173/include/platform_def.h:144: ERROR: code indent should use tabs where possible
+                                MT_IRQ_SEC_SGI_3,      \$

plat/mediatek/mt8173/include/platform_def.h:144: WARNING: please, no spaces at the start of a line
+                                MT_IRQ_SEC_SGI_3,      \$

plat/mediatek/mt8173/include/platform_def.h:145: ERROR: code indent should use tabs where possible
+                                MT_IRQ_SEC_SGI_4,      \$

plat/mediatek/mt8173/include/platform_def.h:145: WARNING: please, no spaces at the start of a line
+                                MT_IRQ_SEC_SGI_4,      \$

plat/mediatek/mt8173/include/platform_def.h:146: ERROR: code indent should use tabs where possible
+                                MT_IRQ_SEC_SGI_5,      \$

plat/mediatek/mt8173/include/platform_def.h:146: WARNING: please, no spaces at the start of a line
+                                MT_IRQ_SEC_SGI_5,      \$

plat/mediatek/mt8173/include/platform_def.h:147: ERROR: code indent should use tabs where possible
+                                MT_IRQ_SEC_SGI_6,      \$

plat/mediatek/mt8173/include/platform_def.h:147: WARNING: please, no spaces at the start of a line
+                                MT_IRQ_SEC_SGI_6,      \$

plat/mediatek/mt8173/include/platform_def.h:148: ERROR: code indent should use tabs where possible
+                                MT_IRQ_SEC_SGI_7$

plat/mediatek/mt8173/include/platform_def.h:148: WARNING: please, no spaces at the start of a line
+                                MT_IRQ_SEC_SGI_7$

plat/mediatek/mt8173/platform.mk:85: WARNING: Duplicate signature
Signed-off-by: Koan-Sin Tan <koansin.tan@gmail.com>
```

**Comment by freedomtan** [comment]
Fixed style problems caught by checkpath. Sorry for forgetting to check with checkpath.

**Comment by danh-arm** [comment]
jenkins: retest this please

**Comment by freedomtan** [comment]
Hi Dan,
  I saw there is build error, but I cannot see what exactly the error is so that I can try to fix it.

**Comment by antonio-nino-diaz-arm** [comment]
It should be enough to rebase on top of master, the error affected the qemu platform, it wasn't your fault and it has been fixed here: https://github.com/ARM-software/arm-trusted-firmware/pull/818
```
lib/libfdt/fdt_ro.c: In function 'fdt_stringlist_count':
lib/libfdt/fdt_ro.c:579:3: error: implicit declaration of function 'strnlen' [-Werror=implicit-function-declaration]
   length = strnlen(list, end - list) + 1;
```

**Comment by danh-arm** [comment]
jenkins: retest this please

**Comment by danh-arm** [comment]
A rebase should not be necessary as there's no conflict files. I've started another build - hopefully this one will be OK now the QEMU problem is fixed.

**Pull request merged**
