### PR TITLE
RK3399 ARM TF clean up 20170210

### PR DESCRIPTION
**Pull request by rkchrome**
Hi,
  So far, it looks like that we have not updated the ARM-TF related codes on upstream for RK3399. In order to prevent the project codes and upstream's of the growing differences, we need to update the latest patches from the Chromium project to synchronize to the upstream.

Which mainly updates following:

1/ updates DDR sleep/resume, and DDR freq features
2/ updates RK3399 M0 features
3/ clean up ARM-TF codes style for RK3399
4/ add supports DDR secure region for accessing on RK3399

BTW, Sorry to accidentally closed the request 20170206 #832, I re-open a new one.

Thanks.

### CODE REVIEW

**Comment by davidcunado-arm** [comment]
jenkins: test this please

**Comment by acgzx** [comment]
It looks like the patch "rockchip: rk3399: disable training modules after DDR DFS" causes some failed, could you show the fail logs?

Thanks

**Comment by sandrine-bailleux-arm** [comment]
Hello,

Indeed, our automated checks show some failures with this patch. It picked up some coding style issues, here is the log:

```
  CHECKING STYLE
plat/rockchip/rk3399/plat_sip_calls.c:91: WARNING: Duplicate signature
Signed-off-by: Lin Huang <hl@rock-chips.com>

plat/rockchip/rk3399/drivers/dram/dfs.c:2062: WARNING: Duplicate signature
Signed-off-by: Lin Huang <hl@rock-chips.com>

plat/rockchip/rk3399/drivers/m0/include/rk3399_mcu.h:35: ERROR: space required after that ';' (ctx:VxV)
+				(*(volatile unsigned int *)(c)); __v;})
 				                                    ^

plat/rockchip/rk3399/drivers/m0/src/main.c:72: WARNING: Duplicate signature
Signed-off-by: Derek Basehore <dbasehore@chromium.org>

plat/rockchip/rk3399/platform.mk:94: WARNING: Duplicate signature
Signed-off-by: Lin Huang <hl@rock-chips.com>

plat/rockchip/rk3399/platform.mk:94: WARNING: Duplicate signature
Signed-off-by: Xing Zheng <zhengxing@rock-chips.com>

plat/rockchip/rk3399/drivers/m0/src/rk3399m0.ld.S:39: WARNING: line over 80 characters
+		ASSERT(. == PARAM_ADDR, "M0 params should go right behind ISR table.");

plat/rockchip/rk3399/drivers/pmu/m0_ctl.h:36: WARNING: please, no space before tabs
+#define M0_BINCODE_BASE ^I((uintptr_t)rk3399m0_bin)$

plat/rockchip/rk3399/include/shared/m0_param.h:329: ERROR: do not set execute permissions for source files

plat/rockchip/rk3399/platform.mk:89: WARNING: Duplicate signature
Signed-off-by: Xing Zheng <zhengxing@rock-chips.com>

plat/rockchip/rk3399/platform.mk:89: WARNING: Duplicate signature
Signed-off-by: Derek Basehore <dbasehore@chromium.org>

plat/rockchip/rk3399/drivers/pmu/pmu.c:1232: WARNING: Duplicate signature
Signed-off-by: Derek Basehore <dbasehore@chromium.org>

plat/rockchip/rk3399/drivers/dram/dfs.c:1005: WARNING: Duplicate signature
Signed-off-by: Derek Basehore <dbasehore@chromium.org>

plat/rockchip/rk3399/drivers/pmu/m0_ctl.c:110: WARNING: Duplicate signature
Signed-off-by: Lin Huang <hl@rock-chips.com>

plat/rockchip/rk3399/drivers/dram/dfs.c:1027: WARNING: Duplicate signature
Signed-off-by: Lin Huang <hl@rock-chips.com>

plat/rockchip/rk3399/drivers/dram/dfs.c:1027: WARNING: Duplicate signature
Signed-off-by: Derek Basehore <dbasehore@chromium.org>

plat/rockchip/rk3399/drivers/dram/dfs.c:1562: WARNING: Duplicate signature
Signed-off-by: Lin Huang <hl@rock-chips.com>

plat/rockchip/rk3399/drivers/dram/dfs.c:1562: WARNING: Duplicate signature
Signed-off-by: Derek Basehore <dbasehore@chromium.org>

plat/rockchip/rk3399/drivers/m0/include/rk3399_mcu.h:47: ERROR: space required after that ',' (ctx:VxV)
+#define MIN(a,b) ((a) < (b) ? (a) : (b))
              ^

plat/rockchip/rk3399/drivers/m0/include/rk3399_mcu.h:48: ERROR: space required after that ',' (ctx:VxV)
+#define MAX(a,b) ((a) > (b) ? (a) : (b))
              ^

plat/rockchip/rk3399/drivers/m0/src/stopwatch.c:74: ERROR: trailing statements should be on next line
+		while (1);

plat/rockchip/rk3399/drivers/m0/src/stopwatch.c:83: WARNING: Missing a blank line after declarations
+	int val = mmio_read_32(SYST_CST);
+	if ((val & COUNTFLAG) || !(val & ENABLE)) {

plat/rockchip/rk3399/drivers/m0/src/stopwatch.c:102: WARNING: Duplicate signature
Signed-off-by: Lin Huang <hl@rock-chips.com>

plat/rockchip/rk3399/drivers/m0/src/stopwatch.c:102: WARNING: Duplicate signature
Signed-off-by: Derek Basehore <dbasehore@chromium.org>

plat/rockchip/rk3399/drivers/m0/src/dram.c:231: WARNING: Duplicate signature
Signed-off-by: Lin Huang <hl@rock-chips.com>

plat/rockchip/rk3399/drivers/m0/src/dram.c:231: WARNING: Duplicate signature
Signed-off-by: Derek Basehore <dbasehore@chromium.org>

plat/rockchip/rk3399/drivers/pmu/pmu.c:1228: WARNING: Duplicate signature
Signed-off-by: Xing Zheng <zhengxing@rock-chips.com>

plat/rockchip/rk3399/drivers/pmu/m0_ctl.c:65: WARNING: Duplicate signature
Signed-off-by: Lin Huang <hl@rock-chips.com>

plat/rockchip/rk3399/drivers/pmu/m0_ctl.c:64: WARNING: Duplicate signature
Signed-off-by: Lin Huang <hl@rock-chips.com>

plat/rockchip/rk3399/drivers/m0/src/dram.c:115: ERROR: do not initialise globals to 0
+uint32_t gatedis_con0 = 0;

plat/rockchip/rk3399/drivers/m0/src/dram.c:213: WARNING: Duplicate signature
Signed-off-by: Derek Basehore <dbasehore@chromium.org>

plat/rockchip/rk3399/drivers/m0/src/dram.c:125: WARNING: Duplicate signature
Signed-off-by: Xing Zheng <zhengxing@rock-chips.com>

plat/rockchip/rk3399/drivers/m0/src/dram.c:39: ERROR: do not initialise statics to 0
+static uint32_t gatedis_con0 = 0;

plat/rockchip/rk3399/rk3399_def.h:83: WARNING: Duplicate signature
Signed-off-by: Xing Zheng <zhengxing@rock-chips.com>

plat/rockchip/rk3399/drivers/soc/soc.h:276: WARNING: please, no space before tabs
+#define SGRF_DDR_RGN_0_16_WMSK^I^I0x0fff ^I/* DDR RGN 0~16 size mask */$

plat/rockchip/rk3399/include/platform_def.h:112: WARNING: Duplicate signature
Signed-off-by: Xing Zheng <zhengxing@rock-chips.com>

plat/rockchip/rk3399/include/shared/bl31_param.h:95: ERROR: do not set execute permissions for source files

plat/rockchip/rk3399/include/shared/bl31_param.h:55: WARNING: Duplicate signature
Signed-off-by: Xing Zheng <zhengxing@rock-chips.com>

plat/rockchip/rk3399/drivers/secure/secure.h:40: WARNING: please, no space before tabs
+#define SGRF_SOC_CON(n) ^I^I(n < 3 ? SGRF_SOC_CON0_1(n) :\$

plat/rockchip/rk3399/drivers/secure/secure.h:68: WARNING: line over 80 characters
+#define SGRF_DDR_RGN_DPLL_CLK		BIT_WITH_WMSK(15) /* DDR PLL output clock */

plat/rockchip/rk3399/drivers/secure/secure.h:69: WARNING: line over 80 characters
+#define SGRF_DDR_RGN_RTC_CLK		BIT_WITH_WMSK(14) /* 32K clock for DDR PLL */

plat/rockchip/rk3399/drivers/secure/secure.h:82: WARNING: please, no space before tabs
+#define SGRF_PMU_CON(n)   ^I^I(SGRF_PMU_CON0 + (n) * 4)$

plat/rockchip/rk3399/drivers/secure/secure.h:120: ERROR: Bad function definition - void secure_watchdog_disable() should probably be void secure_watchdog_disable(void)
+void secure_watchdog_disable();

plat/rockchip/rk3399/drivers/secure/secure.h:121: ERROR: Bad function definition - void secure_watchdog_enable() should probably be void secure_watchdog_enable(void)
+void secure_watchdog_enable();

plat/rockchip/rk3399/drivers/m0/include/rk3399_mcu.h:49: ERROR: space required after that ',' (ctx:VxV)
+#define MIN(a,b) ((a) < (b) ? (a) : (b))
              ^

plat/rockchip/rk3399/drivers/m0/include/rk3399_mcu.h:50: ERROR: space required after that ',' (ctx:VxV)
+#define MAX(a,b) ((a) > (b) ? (a) : (b))
              ^

plat/rockchip/rk3399/drivers/m0/include/rk3399_mcu.h:58: WARNING: Duplicate signature
Signed-off-by: Derek Basehore <dbasehore@chromium.org>

plat/rockchip/rk3399/drivers/dram/suspend.c:735: WARNING: Duplicate signature
Signed-off-by: Derek Basehore <dbasehore@chromium.org>

plat/rockchip/rk3399/drivers/dram/dfs.c:1988: WARNING: Duplicate signature
Signed-off-by: Derek Basehore <dbasehore@chromium.org>

plat/rockchip/rk3399/drivers/m0/src/dram.c:109: WARNING: Duplicate signature
Signed-off-by: Derek Basehore <dbasehore@chromium.org>

plat/rockchip/rk3399/drivers/m0/src/dram.c:109: WARNING: Duplicate signature
Signed-off-by: Xing Zheng <zhengxing@rock-chips.com>

total: 12 errors, 39 warnings, 7033 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

Your patch has style problems, please review.

NOTE: Ignored message types: AVOID_EXTERNS COMPLEX_MACRO FILE_PATH_CHANGES GERRIT_CHANGE_ID GIT_COMMIT_ID NEW_TYPEDEFS VOLATILE

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.
```

Errors should be fixed (except the first one, which looks like a false positive to me), warnings are nice to fix but not mandatory.

There are also some issues in the order of #include in the following files:
```
ERROR:0e09756:plat/rockchip/rk3399/include/platform_def.h:System includes not in order.
ERROR:946b4cd:plat/rockchip/rk3399/drivers/dram/dram.h:System includes not in order.
ERROR:946b4cd:plat/rockchip/rk3399/drivers/m0/src/dram.c:System includes not in order.
ERROR:946b4cd:plat/rockchip/rk3399/drivers/pmu/pmu.h:System includes not in order.
ERROR:e3ed249:plat/rockchip/rk3399/drivers/pmu/m0_ctl.c:System includes not in order.
ERROR:f5c8f26:plat/rockchip/rk3399/drivers/pmu/pmu.c:System includes not in order.
ERROR:2b39dff:plat/rockchip/rk3399/drivers/dram/dfs.c:System include after user include.
ERROR:2b39dff:plat/rockchip/rk3399/drivers/pmu/m0_ctl.c:System includes not in order.
ERROR:2b39dff:plat/rockchip/rk3399/drivers/pmu/pmu.c:System includes not in order.
ERROR:2b39dff:plat/rockchip/rk3399/drivers/soc/soc.c:System includes not in order.
ERROR:98dfda2:plat/rockchip/rk3399/drivers/soc/soc.c:System includes not in order.
```

System header files (#include <blah.h>) should come first in alphabetical order, followed by user header files (#include "blah.h") in alphabetical order.

Regards,
Sandrine

**Comment by rkchrome** [comment]
I try to fix these ERRORs, except the first one:
plat/rockchip/rk3399/drivers/m0/include/rk3399_mcu.h:35: ERROR: space required after that ';' (ctx:VxV)
+				(*(volatile unsigned int *)(c)); __v;})

that you said it which looks like a false positive...

And, add these 3 patches:

a731fd4 rockchip: rk3399: enable secure accessing for SRAM
ae1b4cd rockchip: rk3399: Use tFC value instead of tRFC value
5f6701b rockchip: rk3399: Fix CAS latency setting

Thanks.

**Comment by rkchrome** [comment]
Sorry, and this one:

c778e07 rockchip: Clean up M0 Makefile, clarify float-abi

please help us to review them again. :)

Thanks

**Comment by rkchrome** [comment]
Well, I upload patches again, and fix the first ERROR:

plat/rockchip/rk3399/drivers/m0/include/rk3399_mcu.h:35: ERROR: space required after that ';' (ctx:VxV)
+				(*(volatile unsigned int *)(c)); __v;})

at the commit:

a9a4d23 rockchip: update the raw read/write APIs for M0

--- a/plat/rockchip/rk3399/drivers/m0/include/rk3399_mcu.h
+++ b/plat/rockchip/rk3399/drivers/m0/include/rk3399_mcu.h
@@ -31,9 +31,9 @@
 #ifndef __RK3399_MCU_H__
 #define __RK3399_MCU_H__
 
-#define readl(c)       ({unsigned int __v =    \
+#define mmio_read_32(c)        ({unsigned int __v = \
                                (*(volatile unsigned int *)(c)); __v; })
-#define writel(v, c)   ((*(volatile unsigned int *) (c)) = (v))
+#define mmio_write_32(c, v)    ((*(volatile unsigned int *)(c)) = (v))
...

Thanks.

**Comment by davidcunado-arm** [comment]
jenkins: test this please

**Pull request merged**
