### PR TITLE
Pl061 gpio v4

### PR DESCRIPTION
**Pull request by hzhuang1**
Implement gpio framework and PL061 gpio driver. ARM-software/tf-issues#351

Changelog:
v4:
1. Clean code with more assert.
2. Remove return flag in set_direction() and set_value().
3. Add PLAT_PL061_MAX_GPIOS define.

v3:
1. Add more comments in gpio driver.
2. Add more assert in both gpio & pl061 driver.
3. Add get_direction() in gpio ops.

v2:
1. Update with the standard copyright text.
2. Replace "uint32_t" by "unsigned int" according to the rules in wiki.

### CODE REVIEW

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by danh-arm** [comment]
Review finished. I think we're nearly there now - just minor comments.

**Comment by hzhuang1** [comment]
Close it since v5 version is ready now.

https://github.com/ARM-software/arm-trusted-firmware/pull/518

**Pull request closed without merging**
