### PR TITLE
rockchip: plat_pm.c: Change callbacks implement for our SOCs.

### PR DESCRIPTION
**Pull request by TonyXie06**
Remove struct rockchip_pm_ops_cb and instead of using weak functions
implement; in this way we want the codes look clear and simple;

Change-Id: Ib9e8a5e932fdfc2b3e6a1ec502c40dfe720ac400
Signed-off-by: tony.xie <tony.xie@rock-chips.com>

### CODE REVIEW

**Comment by davidcunado-arm** [comment]
jenkins: test this please

**Comment by davidcunado-arm** [comment]
@TonyXie06 build failure for rk3386:

Build options: CROSS_COMPILE=aarch64-linux-gnu- V=1 DEBUG=1 PLAT=rk3368
...
  CC      plat/rockchip/rk3368/drivers/pmu/pmu.c
aarch64-linux-gnu-gcc -g -DDEBUG=1 -DSKIP_A57_L1_FLUSH_PWR_DWN=0 -DA53_DISABLE_NON_TEMPORAL_HINT=1 -DA57_DISABLE_NON_TEMPORAL_HINT=1 -DERRATA_A53_826319=0 -DERRATA_A53_836870=0 -DERRATA_A57_806969=0 -DERRATA_A57_813420=0 -DERRATA_A57_826974=0 -DERRATA_A57_826977=0 -DERRATA_A57_828024=0 -DERRATA_A57_829520=0 -DERRATA_A57_833471=0 -DARM_CCI_PRODUCT_ID=400 -DARM_ARCH_MAJOR=8 -DARM_ARCH_MINOR=0 -DARM_GIC_ARCH=2 -DASM_ASSERTION=1 -DCOLD_BOOT_SINGLE_CPU=0 -DCTX_INCLUDE_AARCH32_REGS=1 -DCTX_INCLUDE_FPREGS=0 -DENABLE_PLAT_COMPAT=0 -DENABLE_PMF=0 -DENABLE_PSCI_STAT=0 -DENABLE_RUNTIME_INSTRUMENTATION=0 -DERROR_DEPRECATED=0 -DLOAD_IMAGE_V2=0 -DLOG_LEVEL=40 -DNS_TIMER_SWITCH=0 -DPL011_GENERIC_UART=0 -DPLAT_rk3368 -DPROGRAMMABLE_RESET_ADDRESS=0 -DPSCI_EXTENDED_STATE_ID=0 -DRESET_TO_BL31=0 -DSEPARATE_CODE_AND_RODATA=0 -DSPD_none -DSPIN_ON_BL1_EXIT=0 -DTRUSTED_BOARD_BOOT=0 -DUSE_COHERENT_MEM=1 -DAARCH64 -DCRASH_REPORTING=1 -Iinclude/lib/stdlib -Iinclude/lib/stdlib/sys -Iinclude/bl1 -Iinclude/bl31 -Iinclude/common -Iinclude/common/aarch64 -Iinclude/drivers -Iinclude/drivers/arm -Iinclude/drivers/auth -Iinclude/drivers/io -Iinclude/drivers/ti/uart -Iinclude/lib -Iinclude/lib/aarch64 -Iinclude/lib/cpus -Iinclude/lib/cpus/aarch64 -Iinclude/lib/el3_runtime -Iinclude/lib/el3_runtime/aarch64 -Iinclude/lib/pmf -Iinclude/lib/psci -Iinclude/plat/common -Iinclude/services -Iplat/rockchip/common/ -Iplat/rockchip/common/include/ -Iplat/rockchip/common/pmusram -Iplat/rockchip/common/drivers/pmu/ -Iplat/rockchip/rk3368/ -Iplat/rockchip/rk3368/drivers/pmu/ -Iplat/rockchip/rk3368/drivers/soc/ -Iplat/rockchip/rk3368/drivers/ddr/ -Iplat/rockchip/rk3368/include/  -nostdinc -Wmissing-include-dirs -Werror -mgeneral-regs-only -mstrict-align -ffreestanding -fno-builtin -Wall -std=c99 -Os -ffunction-sections -fdata-sections -pedantic -Wno-error=deprecated-declarations  -DIMAGE_BL31 -Wp,-MD,./build/rk3368/debug/bl31/pmu.d -MT build/rk3368/debug/bl31/pmu.o -MP -c plat/rockchip/rk3368/drivers/pmu/pmu.c -o build/rk3368/debug/bl31/pmu.o
plat/rockchip/rk3368/drivers/pmu/pmu.c:407:15: error: variable 'pm_ops' has initializer but incomplete type
 static struct rockchip_pm_ops_cb pm_ops = {
               ^
plat/rockchip/rk3368/drivers/pmu/pmu.c:408:2: error: unknown field 'cores_pwr_dm_on' specified in initializer
  .cores_pwr_dm_on = cores_pwr_domain_on,
  ^
plat/rockchip/rk3368/drivers/pmu/pmu.c:408:21: error: excess elements in struct initializer [-Werror]
  .cores_pwr_dm_on = cores_pwr_domain_on,
                     ^
plat/rockchip/rk3368/drivers/pmu/pmu.c:408:21: note: (near initialization for 'pm_ops')
plat/rockchip/rk3368/drivers/pmu/pmu.c:409:2: error: unknown field 'cores_pwr_dm_on_finish' specified in initializer
  .cores_pwr_dm_on_finish = cores_pwr_domain_on_finish,
  ^
plat/rockchip/rk3368/drivers/pmu/pmu.c:409:28: error: excess elements in struct initializer [-Werror]
  .cores_pwr_dm_on_finish = cores_pwr_domain_on_finish,
                            ^
plat/rockchip/rk3368/drivers/pmu/pmu.c:409:28: note: (near initialization for 'pm_ops')
plat/rockchip/rk3368/drivers/pmu/pmu.c:410:2: error: unknown field 'sys_pwr_dm_suspend' specified in initializer
  .sys_pwr_dm_suspend = sys_pwr_domain_suspend,
  ^
plat/rockchip/rk3368/drivers/pmu/pmu.c:410:24: error: excess elements in struct initializer [-Werror]
  .sys_pwr_dm_suspend = sys_pwr_domain_suspend,
                        ^
plat/rockchip/rk3368/drivers/pmu/pmu.c:410:24: note: (near initialization for 'pm_ops')
plat/rockchip/rk3368/drivers/pmu/pmu.c:411:2: error: unknown field 'sys_pwr_dm_resume' specified in initializer
  .sys_pwr_dm_resume = sys_pwr_domain_resume,
  ^
plat/rockchip/rk3368/drivers/pmu/pmu.c:411:23: error: excess elements in struct initializer [-Werror]
  .sys_pwr_dm_resume = sys_pwr_domain_resume,
                       ^
plat/rockchip/rk3368/drivers/pmu/pmu.c:411:23: note: (near initialization for 'pm_ops')
plat/rockchip/rk3368/drivers/pmu/pmu.c:412:2: error: unknown field 'sys_gbl_soft_reset' specified in initializer
  .sys_gbl_soft_reset = soc_sys_global_soft_reset,
  ^
plat/rockchip/rk3368/drivers/pmu/pmu.c:412:24: error: excess elements in struct initializer [-Werror]
  .sys_gbl_soft_reset = soc_sys_global_soft_reset,
                        ^
plat/rockchip/rk3368/drivers/pmu/pmu.c:412:24: note: (near initialization for 'pm_ops')
plat/rockchip/rk3368/drivers/pmu/pmu.c: In function 'plat_rockchip_pmu_init':
plat/rockchip/rk3368/drivers/pmu/pmu.c:419:2: error: implicit declaration of function 'plat_setup_rockchip_pm_ops' [-Werror=implicit-function-declaration]
  plat_setup_rockchip_pm_ops(&pm_ops);
  ^
cc1: all warnings being treated as errors
make: *** [build/rk3368/debug/bl31/pmu.o] Error 1

**Comment by TonyXie06** [comment]
Only the RK3399 was modified  for this patch, I will submit a patch for RK3368.

**Comment by davidcunado-arm** [comment]
jenkins: test this please

**Pull request merged**
