### PR TITLE
Add "size" function to IO memmap device driver

### PR DESCRIPTION
**Pull request by ljerry**
Hence memmap device can be used to load an image without being wrapped in a
FIP.

Fixes arm-software/tf-issues#371

Signed-off-by: Gerald Lejeune <gerald.lejeune@st.com>

### CODE REVIEW

**Comment by ljerry** [comment]
jenkins: test this please

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by danh-arm** [comment]
jenkins: retest this please

**Pull request merged**
