### PR TITLE
Allwinner PMIC fixes

### PR DESCRIPTION
**Pull request by Andre-ARM**
Fix some minor things we discussed before that didn't make it into the original PR.
This addresses some minor issues during the Allwinner I2C platform setup and improves the code readability on the way. Also this (re-)initialises the I2C controller (again) just before we are using it in the PSCI handler for powering down the system, so we can cope with anything the rich OS may have done meanwhile.
Also this changes the I2C driver stubs for Allwinner and Marvell to be header files instead, and let the actual driver include them.
@Icenowy: Could you please have a look and confirm that these changs are fine? I briefly tested it yesterday on my PineH64 board.
@kostapr: Can you please check that the third patch matches what you were talking about before?

### CODE REVIEW

**Comment by jts-arm** [comment]
IP Review +1

**Comment by apritzel** [comment]
Thanks @smaeul and @kostapr for having a look. Thanks to @jts-arm for the review, makes sense. Will update the PR ASAP.

**Comment by soby-mathew** [comment]
jenkins: test this please

**Comment by antonio-nino-diaz-arm** [comment]
This causes a build error in a80x0 (```make  CROSS_COMPILE=aarch64-linux-gnu- PLAT=a80x0 SCP_BL2=/dev/null  DEBUG=1 V=1 fiptool all```):

```
In file included from drivers/mentor/i2c/mi2cv.c:18:0:
plat/marvell/a8k/common/include/mentor_i2c_plat.h:9:9: error: macro names must be identifiers
 #ifndef 8K_I2C_H
         ^~~~~~~~
drivers/mentor/i2c/mi2cv.c: In function 'mentor_i2c_lost_arbitration':
drivers/mentor/i2c/mi2cv.c:59:41: error: dereferencing pointer to incomplete type 'struct mentor_i2c_regs'
  *status = mmio_read_32((uintptr_t)&base->status);
                                         ^~
drivers/mentor/i2c/mi2cv.c: In function 'mentor_i2c_bus_speed_set':
drivers/mentor/i2c/mi2cv.c:250:11: error: 'CONFIG_SYS_TCLK' undeclared (first use in this function)
    freq = CONFIG_SYS_TCLK / (10 * (m + 1) * (2 << n));
           ^~~~~~~~~~~~~~~
drivers/mentor/i2c/mi2cv.c:250:11: note: each undeclared identifier is reported only once for each function it appears in
drivers/mentor/i2c/mi2cv.c: In function 'i2c_init':
drivers/mentor/i2c/mi2cv.c:454:27: error: 'CONFIG_SYS_I2C_SPEED' undeclared (first use in this function)
  mentor_i2c_bus_speed_set(CONFIG_SYS_I2C_SPEED);
                           ^~~~~~~~~~~~~~~~~~~~
drivers/mentor/i2c/mi2cv.c:462:49: error: 'CONFIG_SYS_I2C_SLAVE' undeclared (first use in this function)
  mmio_write_32((uintptr_t)&base->slave_address, CONFIG_SYS_I2C_SLAVE);
                                                 ^~~~~~~~~~~~~~~~~~~~
```

**Pull request merged**
