### PR TITLE
Pl061 gpio v3

### PR DESCRIPTION
**Pull request by hzhuang1**
Implement gpio framework and PL061 gpio driver. ARM-software/tf-issues#351

Changelog:
v3:
1. Add more comments in gpio driver.
2. Add more assert in both gpio & pl061 driver.
3. Add get_direction() in gpio ops.

v2:
1. Update with the standard copyright text.
2. Replace "uint32_t" by "unsigned int" according to the rules in wiki.

### CODE REVIEW

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by danh-arm** [comment]
You pushed this before I had finished reviewing #509 (again). I've finished reviewing that now but I'm not going to review this PR until all comments from #509 are addressed.

**Comment by hzhuang1** [comment]
Update code with comments in https://github.com/ARM-software/arm-trusted-firmware/pull/512

So close this pull request now.

**Pull request closed without merging**
