### PR TITLE
Tegra denver plat support v3

### PR DESCRIPTION
**Pull request by vwadekar**
Support for "Project Denver" CPU based platforms

### CODE REVIEW

**Comment by vwadekar** [comment]
Previous Pr - #340

**Comment by vwadekar** [comment]
test this please

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by danh-arm** [comment]
test this please

**Comment by danh-arm** [comment]
Varun - Just to let you know that if you add a "test this please" comment, it will have no effect - this has to come from one of the admins.

I have no further comments on this PR so if it passes the checkpatch test, I will merge.

**Comment by vwadekar** [comment]
Thanks Dan.

**Comment by vwadekar** [comment]
Why did the build fail? Not able to click through the details link.

**Comment by danh-arm** [comment]
Just one remaining checkpatch error, Varun. There are a couple of easy to fix warnings too:
```
  CHECKING STYLE
WARNING: Do not use whitespace before Signed-off-by:
#12: 
    Signed-off-by: Varun Wadekar <vwadekar@nvidia.com>

WARNING: Do not use whitespace before Signed-off-by:
#42: 
    Signed-off-by: Varun Wadekar <vwadekar@nvidia.com>

WARNING: Duplicate signature
#42: 
    Signed-off-by: Varun Wadekar <vwadekar@nvidia.com>

WARNING: Possible switch case/default not preceeded by break or fallthrough comment
#156: FILE: plat/nvidia/tegra/common/tegra_sip_calls.c:107:
+	case TEGRA_SIP_AARCH_SWITCH:

WARNING: added, moved or deleted file(s), does MAINTAINERS need updating?
#182: 
new file mode 100644

WARNING: externs should be avoided in .c files
#455: FILE: plat/nvidia/tegra/soc/t132/plat_secondary.c:51:
+extern void tegra_secure_entrypoint(void);

ERROR: that open brace { should be on the previous line
#463: FILE: plat/nvidia/tegra/soc/t132/plat_secondary.c:59:
+static const uint32_t __aligned(8) armv8_trampoline[] =
+{

WARNING: line over 80 characters
#485: FILE: plat/nvidia/tegra/soc/t132/plat_secondary.c:81:
+	tegra_pmc_write_32(PMC_SECURE_SCRATCH22, (unsigned long)&armv8_trampoline);

WARNING: Do not use whitespace before Signed-off-by:
#657: 
    Signed-off-by: Varun Wadekar <vwadekar@nvidia.com>

WARNING: Duplicate signature
#657: 
    Signed-off-by: Varun Wadekar <vwadekar@nvidia.com>

WARNING: Do not use whitespace before Signed-off-by:
#891: 
    Signed-off-by: Varun Wadekar <vwadekar@nvidia.com>

WARNING: Duplicate signature
#891: 
    Signed-off-by: Varun Wadekar <vwadekar@nvidia.com>

WARNING: Do not use whitespace before Signed-off-by:
#1090: 
    Signed-off-by: Varun Wadekar <vwadekar@nvidia.com>

WARNING: Duplicate signature
#1090: 
    Signed-off-by: Varun Wadekar <vwadekar@nvidia.com>

total: 1 errors, 13 warnings, 930 lines checked

NOTE: Ignored message types: COMPLEX_MACRO GERRIT_CHANGE_ID GIT_COMMIT_ID

Your patch has style problems, please review.

If any of these errors are false positives, please report
them to the maintainer, see CHECKPATCH in MAINTAINERS.
```

**Comment by vwadekar** [comment]
Since there were no review comments, I updated this branch with the checkpatch fixes. Please let me know if I should've pushed a new PR.

Verified that "make checkpatch" passes with this series.

Thanks.

**Comment by danh-arm** [comment]
retest this please

**Comment by vwadekar** [comment]
Thanks Dan.

**Pull request merged**
