### PR TITLE
Tegra misc fixes v2

### PR DESCRIPTION
**Pull request by vwadekar**
Previous pull request - #331

### CODE REVIEW

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by danh-arm** [comment]
HI Varun. A quick comment. If you want to submit a new version of your patches and your patches do not contain any review comments, you can simply force push to your existing topic branch and your pull request will be automatically updated. It is only necessary create a new pull request when there are review comments you wish to preserve.

**Comment by danh-arm** [comment]
Also, this PR has conflicts that need resolving.

**Comment by vwadekar** [comment]
Thanks Dan. I accidentally started the previous PR against the master
branch and hence the new PR. If there are no additional comments, I will
push a new PR after a rebase.

**Comment by vwadekar** [comment]
rebased

**Comment by danh-arm** [comment]
test this please

**Comment by danh-arm** [comment]
Varun - I only had very minor comments. Let me know if you want me to merge as-is or wait for an update. Regards, Dan.

**Comment by vwadekar** [comment]
Dan, thanks for the comments. I will push an update on Monday to address
the 2 comments.

**Comment by vwadekar** [comment]
Dan, I was able to get some "me" time today. Pushed a new PR - #337

**Pull request closed without merging**
