### PR TITLE
Add io_emmc support and lower level emmc prototypes

### PR DESCRIPTION
**Pull request by sbranden**
This submission adds upper level io_emmc support to ATF and
provides the function prototypes for necessary lower level
driver.

### CODE REVIEW

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by danh-arm** [comment]
It would seem #558 implements this is a more cleanly abstracted way. Could you confirm? Also, note the license text for this is not going to be acceptable.

**Comment by sbranden** [comment]
The MMC implementation may likely be the way to go.  This contribution can be used as reference for additional functionality.

**Comment by danh-arm** [comment]
Closing this PR as it will not merged in its current form and may be superseded by the other implementation

**Pull request closed without merging**
