### PR TITLE
Atf master+linaro warp7 squash

### PR DESCRIPTION
**Pull request by bryanodonoghue**
This is the second version of this PR.

As discussed in this PR https://github.com/ARM-software/arm-trusted-firmware/pull/1490#issuecomment-407427892

1. "smc #0" fix has been resolved by passing ARM_CORTEX_A7=yes and this has been documented @danh-arm 
2. plat/imx becomes plat/imx/imx8
3. The WaRP7 stuff goes under plat/imx/imx7
4. As requested alot of patches have been squashed down from ~150 patches to about 90 @danh-arm @antonio-nino-diaz-arm ,  I could squash these patches down further but, my own feeling is that the resulting patches would be huge.
5. Also producing a single PR as we discussed in the pervious PR, as opposed to the first proposal of ~13 separate PRs of about 10 commits each

On point #5 if this PR is too big, it's no problem to split it up into a series of PRs, just let me know.

I ended up pulling apart patches from @rmsilva but since the code hasn't changed I have maintained his SOB

@Anson-Huang @omnium21

### CODE REVIEW

**Comment by Anson-Huang** [comment]
For the file directory change of imx8 platforms, Acked-by: Anson Huang <Anson.Huang@nxp.com>

**Comment by Anson-Huang** [comment]
For the file directory change of imx8 platforms, Acked-by: Anson Huang <Anson.Huang@nxp.com>

Anson Huang
Best Regards!
[cid:image002.png@01D39624.69C9AC90]

**Comment by danh-arm** [comment]
This PR is undigestible. There are far too many commits. This project is not interested in the history of changes to the platform port. There should be no more than 10 commits in total, something along the lines of:
1. Generic refactoring to support future IMX7 platform
2. IMX platform refactoring to support future IMX7 platform
3. Add minimally functional IMX7 platform
4. IMX7: Add feature X
5. Documentation for IMX7 platform

Regards

Dan.

**Comment by danh-arm** [comment]
Also, please target PRs to the integration branch, not the master branch

**Pull request closed without merging**
