### PR TITLE
Tegra186 platform support v5

### PR DESCRIPTION
**Pull request by vwadekar**
Tegra186 platform support - batch #5

### CODE REVIEW

**Comment by vwadekar** [comment]
@davidcunado-arm 

Request you review at your earliest. Thanks.

**Comment by davidcunado-arm** [comment]
jenkins: test this please

**Comment by davidcunado-arm** [comment]
@vwadekar 
Apologies for the delay - we had issues with our internal CI, which delayed testing of the patch; all resolved now.

**Comment by vwadekar** [comment]
@davidcunado-arm 

Thanks

**Pull request merged**
