### PR TITLE
fix sunxi h6 memory map

### PR DESCRIPTION
**Pull request by armlabs**

### CODE REVIEW

**Comment by Andre-ARM** [comment]
I put this into gerrit, under my name due to the lack of an actual name or email of "armlabs":
https://review.trustedfirmware.org/c/TF-A/trusted-firmware-a/+/3687

**Comment by joannafarley-arm** [comment]
Cleaning up.

**Comment by joannafarley-arm** [comment]
Cleaning up.

**Comment by joannafarley-arm** [comment]
Cleaning up.

**Pull request closed without merging**
