### PR TITLE
Replace stdio.h functions by TF functions

### PR DESCRIPTION
**Pull request by antonio-nino-diaz-arm**
Functions provided by stdio.h such as printf and sprintf are available in the codebase, but they add a lot of code to the final image if they are used:

- AArch64: ~4KB
- AArch32: ~2KB in T32, ~3KB in A32

tf_printf and tf_snprintf are a lot more simple, but it is preferable to use them when possible because they are also used in common code.

### CODE REVIEW

**Comment by hzhuang1** [comment]
Acked

**Comment by dp-arm** [comment]
jenkins: test this please

**Comment by Yann-lms** [comment]
I've seen with this PR that I forgot to add drivers/st and include/drivers/st in the list of files. I will push a patch for this when I'm back to office.

@ldebieve will be able to check this patch as well as the other patches impacting STM32MP1 platform.

**Comment by antonio-nino-diaz-arm** [comment]
Sorry, @Yann-lms. Now that we have the bot that checks the maintainers affected by each patch I don't check manually...

**Comment by ldebieve** [comment]
Acked

OK for me on STM32MP1 platform

**Comment by antonio-nino-diaz-arm** [comment]
@ldebieve If you want me to add you to the commit message as acked, paste the corresponding ``Acked-by:`` line here (I can't see your email or anything).

**Pull request merged**
