### PR TITLE
hikey*: Add LOAD_IMAGE_V2 and OP-TEE header parsing support

### PR DESCRIPTION
**Pull request by vchong**
@hzhuang1 Please ack! Thanks!

### CODE REVIEW

**Comment by davidcunado-arm** [comment]
jenkins: test this please

**Comment by davidcunado-arm** [comment]
jenkins: retest this please

**Comment by davidcunado-arm** [comment]
@hzhuang1 
Can you review this change? Thanks!

**Comment by hzhuang1** [comment]
Acked.

**Pull request merged**
