### PR TITLE
add MMC driver v1

### PR DESCRIPTION
**Pull request by hzhuang1**
Add MMC driver to fix the issue in below.

https://github.com/ARM-software/tf-issues/issues/376

### CODE REVIEW

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by danh-arm** [comment]
One high level comment on this: You seem to use the terms MMC and eMMC interchangeably, when one is a subset of the other. Can you use eMMC throughout (including the code) or explicitly have separate MMC and eMMC layers to make it clear which features belong to which.

**Comment by hzhuang1** [comment]
OK. I'll use emmc instead.

**Comment by hzhuang1** [comment]
Split this pull request with two. One is for emmc & io_block driver. And the other one is for dwmmc driver.
https://github.com/ARM-software/arm-trusted-firmware/pull/573
https://github.com/ARM-software/arm-trusted-firmware/pull/574

**Pull request closed without merging**
