### PR TITLE
submit arm pl061 gpio driver based on integration branch

### PR DESCRIPTION
**Pull request by hzhuang1**
Implement gpio framework and PL061 gpio driver. ARM-software/tf-issues#351

### CODE REVIEW

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by hzhuang1** [comment]
My branch is at here. https://github.com/hzhuang1/arm-trusted-firmware/commits/pl061_gpio

Why I can't see my commit in this pull request? I can only see something below.

 hzhuang1 commented 5 minutes ago

Implement gpio framework and PL061 gpio driver. ARM-software/tf-issues#351
jcastillo-arm and others added some commits on Nov 7, 2015
	@jcastillo-arm 	ARM plat: add build option to unlock access to non-secure timer … 	
0e5dcdd
	@sorenb-xlnx 	cdefs.h: Use __deprecated__ instead of deprecated … 	
6b8d672
	@danh-arm 	Merge pull request #495 from jcastillo-arm/jc/tf-issues/170 … 	01fc3f7
	@danh-arm 	Merge pull request #496 from Xilinx/attr-deprecated … 	870d881

**Comment by hzhuang1** [comment]
Use https://github.com/ARM-software/arm-trusted-firmware/pull/500 to replace.

I'm very sorry on confusion.

**Pull request closed without merging**
