### PR TITLE
Tegra186 platform support v3

### PR DESCRIPTION
**Pull request by vwadekar**
Tegra186 platform code batch #3

### CODE REVIEW

**Comment by vwadekar** [comment]
@davidcunado-arm @danh-arm 

Hello,

Can you please review this PR? Thanks

**Comment by davidcunado-arm** [comment]
@vwadekar 
Apologies for the delay - will review on Wednesday.

**Comment by davidcunado-arm** [comment]
jenkins: test this please

**Comment by vwadekar** [comment]
@davidcunado-arm 

Thanks

**Pull request merged**
