### PR TITLE
Improvements to setup page tables code

### PR DESCRIPTION
**Pull request by antonio-nino-diaz-arm**
The idea behind this PR is to make the current ``arm_setup_page_tables`` reusable by all platforms. There are already a few platforms using it, and it creates problems such as: https://github.com/ARM-software/arm-trusted-firmware/commit/e8fae4bc64c9bcd1af79ac1943aa51b4c908ca2e

This patch refactors all the code related to that function and removes ``ARM_XLAT_TABLES_LIB_V1`` from non-Arm platform code. The non-Arm platforms that are affected are k3, qemu and zynqmp, which now use the newly introduced ``setup_page_tables``.

### CODE REVIEW

**Comment by antonio-nino-diaz-arm** [comment]
The CI failures are just some MISRA defects.

**Comment by jenswi-linaro** [comment]
OK for plat/qemu

**Comment by glneo** [comment]
Looks fine for plat/ti

**Comment by antonio-nino-diaz-arm** [comment]
jenkins: test this please

**Pull request merged**
