### PR TITLE
Enable pmf rt instr hikey

### PR DESCRIPTION
**Pull request by vingu-linaro**
This patch enable PMF and runtime instrumentation for hikey

### CODE REVIEW

**Comment by danh-arm** [comment]
jenkins: test this please

**Comment by danh-arm** [comment]
Hi @hzhuang1. Can you ack this? It looks OK to me.

**Comment by hzhuang1** [comment]
Acked.

Are these register definitions only for hikey? Do we have the same register definitions on hikey960? If they're same, maybe we can write it as common code.

**Comment by danh-arm** [comment]
I agree this code could be shared with hikey960 but that will be easier to do after hikey960 is integrated. There's no need to delay this PR.

**Comment by vingu-linaro** [comment]
I haven't look in details hikey960 code but this code doesn't use anything specific to hikey so it should be easy to add hikey960 support in a 2nd step after it has been integrated

**Comment by danh-arm** [comment]
jenkins: retest this please

**Comment by danh-arm** [comment]
We're having infrastructure issues with this...

**Comment by danh-arm** [comment]
jenkins: retest this please

**Pull request merged**
