### PR TITLE
TLK dispatcher

### PR DESCRIPTION
**Pull request by vwadekar**
This topic branch adds the TLK dispatcher to the mix. This dispatcher helps TLK to run with the Trusted Firmware.

Verification: Code compiles with the master branch.

### CODE REVIEW

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by vwadekar** [comment]
Thanks Achin. Will push an update shortly.

**Comment by achingupta** [comment]
Hi Varun,

I will have some more comments/questions over the next couple of days. You might want to hold off the pull request until then. Just to save you the possible trouble of having to raise the pull request again. I will drop you a line when I am done (most likely Wednesday). I hope that works for you.

Thanks,
Achin


________________________________________

**Comment by vwadekar** [comment]
Thanks Achin. Will wait till you review the entire patch. FWIW, I pushed an update today to fix the previous comments.

**Comment by achingupta** [comment]
The copyright and license text in the files you are contributing should be the same as the rest of ARM Trusted Firmware code. Could you please remove the NVidia copyright text?

**Comment by vwadekar** [comment]
Created another PR for fixed-v1 branch.

**Pull request closed without merging**
