### PR TITLE
TLK dispatcher

### PR DESCRIPTION
**Pull request by vwadekar**
This topic branch adds the TLK dispatcher to the mix. This dispatcher helps TLK to run with the Trusted Firmware.

Verification: Code compiles with the master branch.

v1: fixes comments from tlkd branch.
v2: fixes comments from tlkd-fixed-v1 branch.

### CODE REVIEW

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by achingupta** [comment]
@vwadekar. Thanks for rolling in my feedback. @soby-mathew and @danh-arm will have a look as well next week to complete the review.

**Comment by vwadekar** [comment]
Thanks Achin. Appreciate the help.

**Comment by danh-arm** [comment]
test this please

**Comment by vwadekar** [comment]
Dan, I have verified compilation only as there is no platform support for
Tegra in the Trusted Firmware now.

**Comment by danh-arm** [comment]
Hi Varun. Please ignore the comments saying "test this please" and "Can one of the admins verify this patch?" comments. They are related to our internal CI infrastructure, not directed at you! Regards, Dan.

**Comment by danh-arm** [comment]
HI Varun. I've finished looking at this - it mainly looks good. The items labelled "nit" are optional to fix but I think a few small changes will make this more robust to bad NS code. Regards, Dan.

**Comment by vwadekar** [comment]
Thanks Dan. I will fix the nits and push a new PR tomorrow.

**Comment by vwadekar** [comment]
Pushed tlkd-fixed-v3 to fix Dan's comments.

**Pull request closed without merging**
