### PR TITLE
add note re: SPDX identifiers in files

### PR DESCRIPTION
**Pull request by jlovejoy**
added note at bottom regarding use of SPDX identifiers following this example: https://github.com/pocoproject/poco/blob/develop/LICENSE

### CODE REVIEW

**Comment by danh-arm** [comment]
Looks good @jlovejoy but could you add your "Signed-off-by:" to the commit message as per the contributing guidelines:
https://github.com/ARM-software/arm-trusted-firmware/blob/master/contributing.md#submitting-changes

**Comment by danh-arm** [comment]
A couple of other minor comments;

- You could update the Copyright end year to 2017.

- Would be good to say in the commit title that license.md is being updated (e.g. "Add note re: SPDX identifiers in license.md").

**Comment by davidcunado-arm** [comment]
Hi @jlovejoy could you merge these 2 commits into single commit?

**Comment by danh-arm** [comment]
Superseded by #944

**Pull request closed without merging**
