### PR TITLE
Tegra: support PSCI v1.0 framework implementation

### PR DESCRIPTION
**Pull request by vwadekar**
This patch modifies the Tegra port to support the new PSCI v1.0
implementation. This includes modifications to the power management
and platform topology code.

Signed-off-by: Varun Wadekar <vwadekar@nvidia.com>

### CODE REVIEW

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by danh-arm** [comment]
test this please

**Comment by achingupta** [comment]
@vwadekar 

Hi Varun,

FYI. We are having a close look at your pull request to understand how the two Tegra variants (T132 & T210) make use of the extended state ID and topology description support. We should have some feedback next week at the earliest and possibly some more questions interim. 

thanks,
Achin

**Comment by vwadekar** [comment]
Thanks Achin. Let me know if there are any obvious issues with the
implementation.

**Comment by vwadekar** [comment]
@soby-mathew 

Thanks. Will take a look and respond.

**Comment by vwadekar** [comment]
New PR - #372

**Pull request closed without merging**
