### PR TITLE
Replace ASM signed tests with unsigned

### PR DESCRIPTION
**Pull request by douglas-raillard-arm**

### CODE REVIEW

**Comment by davidcunado-arm** [comment]
@vwadekar
Can you review  / approve the change to the tegra platform port?

**Comment by vwadekar** [comment]
@davidcunado-arm 

The change looks good. I would prefer the commit message tag to be  "Tegra" instead of "tegra" to keep the history consistent.

**Comment by douglas-raillard-arm** [comment]
@vwadekar: tegra changed to Tegra.

**Comment by vwadekar** [comment]
@douglas-raillard-arm 

Thanks. Looks good. Please add my Ack.

**Comment by douglas-raillard-arm** [comment]
I added your Acked-by, thanks.

**Pull request merged**
