### PR TITLE
Fix order of includes

### PR DESCRIPTION
**Pull request by islmit01**

### CODE REVIEW

**Comment by davidcunado-arm** [comment]
@hzhuang1 , @mtk01412 , @vwadekar , @jenswi-linaro , @rkchrome, @sorenb-xlnx 
FYI - some minor changes to your platforms; we'll aim to merge WED / THU this, week - please let me know before then if you have any concerns!
Thanks!

**Comment by masahir0y** [comment]
Hi.  I was not tracking this PR, but I've just noticed some changes are suspicious.

As discussed in PR #929, mixing system headers (outside of this project) and project local headers is a bad idea, and @davidcunado-arm agreed.


    diff --git a/tools/fiptool/fiptool.c b/tools/fiptool/fiptool.c
    index 4d80f2f16632..65e4a25c479a 100644
    --- a/tools/fiptool/fiptool.c
    +++ b/tools/fiptool/fiptool.c
    @@ -19,7 +19,6 @@
     #include <unistd.h>
     
     #include <openssl/sha.h>
    -
     #include <firmware_image_package.h>
     
     #include "fiptool.h"

I think the blank line was intentionally inserted to split the different header groups.

    diff --git a/tools/fiptool/fiptool.h b/tools/fiptool/fiptool.h
    index 4b5cdd91f22a..889b0fde58a7 100644
    --- a/tools/fiptool/fiptool.h
    +++ b/tools/fiptool/fiptool.h
    @@ -7,10 +7,11 @@
     #ifndef __FIPTOOL_H__
     #define __FIPTOOL_H__
     
    +#include <firmware_image_package.h>
    +
     #include <stddef.h>
     #include <stdint.h>
     
    -#include <firmware_image_package.h>
     #include <uuid.h>
     
     #define NELEM(x) (sizeof (x) / sizeof *(x))

firmware_image_package.h and uuid.h belong to the same group.
(they are both located in include/tools_share)

Mixing them with system headers is a bad idea, in my opinion.


    diff --git a/tools/fiptool/tbbr_config.c b/tools/fiptool/tbbr_config.c
    index 7c6c24be4ff1..6231cd4edda5 100644
    --- a/tools/fiptool/tbbr_config.c
    +++ b/tools/fiptool/tbbr_config.c
    @@ -4,9 +4,8 @@
      * SPDX-License-Identifier: BSD-3-Clause
      */
 
    -#include <stddef.h>
    -
     #include <firmware_image_package.h>
    +#include <stddef.h>
     
     #include "tbbr_config.h"
 
stddef.h is a system header, and firmware_image_package.h is local to this project.
Heades were listed public -> local order.

**Comment by davidcunado-arm** [comment]
@masahir0y 
I'll take a look - we did aim to keep the system header separation as was discussed in other PRs, but clearly we missed a few cases (which can happen in these types of changes).

**Comment by masahir0y** [comment]
@davidcunado-arm 
Thanks!

Perhaps, one possible idea to avoid a step backward in the future is to insert comment lines as separators.
I leave this up to the maintainers.

     /* system headers */
     #include <stddef.h>
     #include <stdint.h>
     /* include/tools_share */
     #include <firmware_image_package.h>
     #include <uuid.h>

**Comment by davidcunado-arm** [comment]
@masahir0y 
FYI - we're raised PR #1044 to address this issue.

**Pull request merged**
