### PR TITLE
Introduce the new framework for PSCIv1.0

### PR DESCRIPTION
**Pull request by soby-mathew**
This patch stack introduces the new framework to support
the power domain topology and composite power state as specified in
PSCI v1.0 specification better. As a result of these framework changes,
the platform API has changed as well. A platform compatibility layer is
implemented to ensure that the existing platform ports using the old
platform API will continue to work with minimal changes. Care is also taken
to enable the SPDs to continue to work even if the compatibility layer is
disabled.

### CODE REVIEW

**Comment by achingupta** [comment]
@vwadekar 

Hi Varun,

This pull request implements a considerable amount of churn in the PSCI implementation. The aims behind the churn are:

1.  Remove the framework assumption about the structure of the MPIDR and its relation to the power domain topology. This also enables deeper and more complex hierarchies to be supported.
2.  Rework the power state coordination implementation in the framework to support the more detailed PSCI 1.0 requirements and reduce the platform port complexity.
3.  Enable the use of the extended power_state parameter and the larger StateID field in the PSCI CPU_SUSPEND API

The new PSCI implementation introduces new frameworks to fulfill the above aims. These framework changes have resulted in changes to the platform porting API as well. 

To minimise the impact on existing platform ports, we have provided a compatibility layer that implements the new platform APIs using the old APIs. The build flag ENABLE_PLAT_COMPAT specifies whether to enable this layer or not. The layer is enabled by default. A detailed platform migration guide can be found [here](https://github.com/soby-mathew/arm-trusted-firmware/blob/e7f50121ef65a6d383d75b7ede638dfbdc416e64/docs/platform-migration-guide.md).

As a consequence of the changes to the platform porting interface some changes were required to the SPDs as well. The APIs used by the TLKD to retrieve the linear CPU index and initialise the context of the current CPU have been changed. The changes can be found [here](https://github.com/soby-mathew/arm-trusted-firmware/commit/406349e9c859906deeb378bc09a9506bc451f1b2#diff-40661cc57b28dd655bd27e77a7f374e6R124).

I am assuming that you would not be interested in immediately migrating to the new platform porting interface. However, could you use this PR to:

1.  test whether the Tegra ports still work as expected using the compatibility layer
2.  sign-off the changes to the TLKD
3.  raise any concerns with the new platform porting interface or the PSCI implementation

We intend to merge the pull request early next week. Would you be able to take it out for a spin and comment by then? Please let us know if anything is unclear.

cheers,
Achin

**Comment by vwadekar** [comment]
Hello Achin,

I will verify this PR on T132/T210 platforms and update my findings here, before end of this week. Although, we do not plan to move to PSCIv1.0 immediately - mostly due to the lack of v1.0 support in the linux driver, if this code works well with PSCI v0.2 kernel driver, then we might move.

Some immediate questions:

1. Does the new code require any modifications to the linux kernel driver?
2. Will this PR run with linux kernel supporting PSCI v0.2?
3. Are you planning on attaching an end-of-life date for the compat layer? This could mandate when Tegra/TLK has to move to PSCI v1.0

Will ask more questions down the line.

Thanks.

**Comment by achingupta** [comment]
Hi Varun,

On Mon, Aug 03, 2015 at 10:56:07AM +0100, varunw-nvidia wrote:
> Hello Achin,
>
> I will verify this PR on T132/T210 platforms and update my findings here, before end of this week. Although, we do not plan to move to PSCIv1.0 immediately - mostly due to the lack of v1.0 support in the linux driver, if this code works well with PSCI v0.2 kernel driver, then we might move.
>
> Some immediate questions:
>
>  1.  Does the new code require any modifications to the linux kernel driver?
>  2.  Will this PR run with linux kernel supporting PSCI v0.2?

The PSCIv1.0 spec is backwards compatible with PSCIv0.2 apart from minor
deviations e.g. an invalid address in a CPU_ON call is reported using the error
code 'INVALID_ADDRESS' instead of 'INVALID_PARAMETERS', the scope of
AFFINITY_INFO has been reduced to just the CPU power domain etc.

So, I expect the v0.2 Linux driver to work with the new PSCI implementation as
long as 'PSCI_EXTENDED_STATE_ID' build flag is not enabled by the platform since
the driver still uses the original power state format. We have smoke tested this
internally and saw no discrepancies. We did not have to make any changes to the
Linux driver.

The ARM TF PSCI implementation already reports the version as 1.0. We still do
not implement most of the optional features. So, in a way you are already using
PSCIv1.0.

The intention behind these changes was to simplify the implementation and
increase its scalability w.r.t complex power domain topologies and power
states. The bigger question is when you would like to move to the new porting
interface. You could continue using the v0.2 driver even after having updated
your platform ports. This is what happens by default on the ARM development
platforms.

>  3.  Are you planning on attaching an end-of-life date for the compat layer? This could mandate when Tegra/TLK has to move to PSCI v1.0

We do not have an end-of-life of life in mind at the moment. New PSCI APIs will
be developed using the new platform porting interface as a basis.

Any new platform APIs needed to implement these new PSCI APIs will not be
backported to the old platform interface e.g. if we add CPU_FREEZE and it needs
a platform hook then this hook will be added to `plat_psci_ops_t` and not to the
old `plat_pm_ops_t`.

If it is possible to implement a new PSCI API without any platform specific
changes then I don't think we will have the bandwidth to test whether the API
works as expected on the old platform ports.

The bottom line being that to use any PSCI APIs that will be implemented in the
future, it is extremely likely that you will have to move to the new platform
porting interface.

Do let us know if this sounds reasonable to you?


>
> Will ask more questions down the line.

Thanks a lot. We will wait for all your feedback before rolling it in and
updating the PR.

cheers,
Achin

>
> Thanks.
>
> �
> Reply to this email directly or view it on GitHub<https://github.com/ARM-software/arm-trusted-firmware/pull/346#issuecomment-127181424>.

-- IMPORTANT NOTICE: The contents of this email and any attachments are confidential and may also be privileged. If you are not the intended recipient, please notify the sender immediately and do not disclose the contents to any other person, use it for any purpose, or store or copy the information in any medium.  Thank you.

ARM Limited, Registered office 110 Fulbourn Road, Cambridge CB1 9NJ, Registered in England & Wales, Company No:  2557590
ARM Holdings plc, Registered office 110 Fulbourn Road, Cambridge CB1 9NJ, Registered in England & Wales, Company No:  2548782

**Comment by jbech-linaro** [comment]
Hi @achingupta 

I've checked the relevant parts and I think this should be OK for us. We are only calling `platform_get_core_pos(mpidr)` directly which I still think should be OK. Feel free to add an acked-by from me.

\\ Regards Joakim

**Comment by soby-mathew** [comment]
I accidentally updated previous version for this PR. Please find the comment given by Varun on the previous version here:

https://github.com/soby-mathew/arm-trusted-firmware/commit/406349e9c859906deeb378bc09a9506bc451f1b2#diff-40661cc57b28dd655bd27e77a7f374e6R124

**Comment by vwadekar** [comment]
Hi @soby-mathew, @achingupta,

I have started modifying the platform port according to the docs, but I see the following ASSERT during CPU suspend.

ASSERT: psci_cpu_suspend <103> : psci_validate_suspend_req(&state_info, is_power_down_state) == PSCI_E_SUCCESS

I debugged further and found out that psci_find_target_suspend_lvl() is returning an error. Any pointers to solve this problem?

**Comment by vwadekar** [comment]
One more Q - Is there an alternative to psci_get_max_phys_off_afflvl() with the new API?

**Comment by achingupta** [comment]
@vwadekar 

Hi Varun,

Thanks for providing the feedback!

Just need to clarify this first: Are you enabling the compatibility layer to ensure that the Tegra port works as before or are you implementing the changes to move to the new platform porting interface and reworking the Tegra port as a result?

Regarding `psci_get_max_phys_off_afflvl()`, I am not sure if I understand the context. If you have enabled the compatibility layer then this function is implemented in psci_common.c. If not, then the platform hooks can derive this information from the `psci_power_state_t` parameter.

Please let me know if I am missing anything.

Thanks,
Achin

**Comment by vwadekar** [comment]
@achingupta 

Apologies, I forgot to mention that I am not using the compatibility layer and trying to re-work the Tegra port to support the new API.

We need to use psci_get_max_phys_off_afflvl() to check if the max affinity level that is being powered up is MPIDR_AFFLVL1. If yes, then we need to program a certain bit to indicate this to the power management processor.

I think we can first check the asserts. In the background, I will try to see if I get a solution for the psci_get_max_phys_off_afflvl() usage.

**Comment by achingupta** [comment]
Hi Varun,

On 06/08/15 12:46, varunw-nvidia wrote:

@achingupta<https://github.com/achingupta>

Apologies, I forgot to mention that I am not using the compatibility layer and trying to re-work the Tegra port to support the new API.

Ah okie! Would it be possible for you to do a quick run with the compatibility layer as well. It would give us a lot of confidence in that we have not broken existing ports.


We need to use psci_get_max_phys_off_afflvl() to check if the max affinity level that is being powered up is MPIDR_AFFLVL1. If yes, then we need to program a certain bit to indicate this to the power management processor.

I think we can first check the asserts. In the background, I will try to see if I get a solution for the psci_get_max_phys_off_afflvl() usage.

You should not have to rely on a function similar to psci_get_max_phy_off_afflvl(). When the hooks to turn off power domains are called (`pwr_domain_suspend()`, `pwr_domain_off()`), the target power state for each power level is passed in the  `psci_power_state_t` parameter. The highest power level for which the target is OFF is what you are looking for. The `is_local_state_off()` macro can be used to perform the check.


Also the changes to `validate_power_state()` that introduce and use the `PLAT_MAX_SUSPEND_STATE` constant to get CPU_SUSPEND working (please see your earlier comment) are not required. Could you please provide some more details? If a power down state has been requested through CPU_SUSPEND, then atleast a single power level's requested local state would be OFF. This is what `psci_find_target_suspend_lvl()` looks for. The assertion should not fire in this case.

thanks a lot,
Achin

—
Reply to this email directly or view it on GitHub<https://github.com/ARM-software/arm-trusted-firmware/pull/346#issuecomment-128339733>.


-- IMPORTANT NOTICE: The contents of this email and any attachments are confidential and may also be privileged. If you are not the intended recipient, please notify the sender immediately and do not disclose the contents to any other person, use it for any purpose, or store or copy the information in any medium. Thank you.

ARM Limited, Registered office 110 Fulbourn Road, Cambridge CB1 9NJ, Registered in England & Wales, Company No: 2557590
ARM Holdings plc, Registered office 110 Fulbourn Road, Cambridge CB1 9NJ, Registered in England & Wales, Company No: 2548782

**Comment by vwadekar** [comment]
@achingupta 

Thanks Achin.

I was looking at this code snippet.

<snip>

int psci_cpu_suspend(unsigned int power_state,
		     uintptr_t entrypoint,
		     unsigned long context_id)
{
	int rc;
	unsigned int target_pwrlvl, is_power_down_state;
	entry_point_info_t ep;
	psci_power_state_t state_info = { {0} };
	plat_local_state_t cpu_pd_state;

	/* Validate the power_state parameter */
	rc = psci_validate_power_state(power_state, &state_info);
	if (rc != PSCI_E_SUCCESS) {
		assert(rc == PSCI_E_INVALID_PARAMS);
		return rc;
	}

	/*
	 * Get the value of the state type bit from the power state parameter.
	 */
	is_power_down_state = psci_get_pstate_type(power_state);

	/* Sanity check the requested suspend levels */
	assert (psci_validate_suspend_req(&state_info, is_power_down_state)
			== PSCI_E_SUCCESS);
<snip>

The second parameter to psci_validate_power_state(), is un-initialized and passed to the platform code. Does this mean that the platform is supposed to fill in the state info?

I have the following code in my _validate_power_state() handler for Tegra.

<snip>
/*******************************************************************************
 * Platform power states
 ******************************************************************************/
#define PLAT_MAX_RET_STATE	1
#define PLAT_MAX_SUSPEND_STATE	2
#define PLAT_MAX_OFF_STATE	3

int32_t tegra_soc_validate_power_state(unsigned int power_state,
					psci_power_state_t *req_state)
{
	int pwr_lvl = psci_get_pstate_pwrlvl(power_state);
	int state_id = psci_get_pstate_id(power_state);

	/* Sanity check the requested afflvl */
	if (psci_get_pstate_type(power_state) == PSTATE_TYPE_STANDBY) {
		/*
		 * It's possible to enter standby only on affinity level 0 i.e.
		 * a cpu on Tegra. Ignore any other affinity level.
		 */
		if (pwr_lvl != MPIDR_AFFLVL0)
			return PSCI_E_INVALID_PARAMS;

		/* power domain in standby state */
		req_state->pwr_domain_state[pwr_lvl] = PLAT_MAX_RET_STATE;
	}

	/* Sanity check the requested state id */
	if (state_id != PLAT_SYS_SUSPEND_STATE_ID) {
		ERROR("unsupported state id\n");
		return PSCI_E_NOT_SUPPORTED;
	}

	/* Get the suspend state-id */
	suspend_id = state_id;
	flush_dcache_range((uint64_t)&suspend_id, sizeof(suspend_id));

	/* power domain in suspend state */
	req_state->pwr_domain_state[MPIDR_AFFLVL0] = PLAT_MAX_SUSPEND_STATE;

	return PSCI_E_SUCCESS;
}
<snip>

If I remove the lines to set "req_state->pwr_domain_state", then the asserts are seen.

Will try the compat code and let you know if I see any issues.

Thanks.

**Comment by vwadekar** [comment]
@achingupta @soby-mathew 

I have pushed my code to github. The Tegra support is present @ https://github.com/vwadekar/arm-trusted-firmware/commit/36e12d954ed7cd3e278ebed38674c4f1204e8b53.

Please let me know if there's any issues with the way I have implemented the code which is leading to the asserts.

**Comment by vwadekar** [comment]
I verified the Tegra port with the compatibility layer and all things work fine. I have updated one change that I had to do in plat_pm_compat.c. Else the platform worked (basic boot, secondary CPU ON/OFF, cpu suspend, system suspend) out of the box. Thanks.

**Comment by achingupta** [comment]
Hi `,

On 07/08/15 05:26, varunw-nvidia wrote:> @achingupta <https://github.com/achingupta>
>
> Thanks Achin.
>
> I was looking at this code snippet.
>
> int psci_cpu_suspend(unsigned int power_state,
> uintptr_t entrypoint,
> unsigned long context_id)
> {
> int rc;
> unsigned int target_pwrlvl, is_power_down_state;
> entry_point_info_t ep;
> psci_power_state_t state_info = { {0} };
> plat_local_state_t cpu_pd_state;
>
> |/* Validate the power_state parameter */
> rc = psci_validate_power_state(power_state, &state_info);
> if (rc != PSCI_E_SUCCESS) {
>      assert(rc == PSCI_E_INVALID_PARAMS);
>      return rc;
> }
>
> /*
>   * Get the value of the state type bit from the power state parameter.
>   */
> is_power_down_state = psci_get_pstate_type(power_state);
>
> /* Sanity check the requested suspend levels */
> assert (psci_validate_suspend_req(&state_info, is_power_down_state)
>          == PSCI_E_SUCCESS);
> |
>
> The second parameter to psci_validate_power_state(), is un-initialized and
> passed to the platform code. Does this mean that the platform is supposed to
> fill in the state info?

Yes! The purpose of `psci_validate_power_state()` is to transform the either format of the `power_state` parameter (original & extended) into a generic representation that the PSCI implementation can use. The transformation is done by the `validate_power_state()` platform hook. The `psci_power_state_t *state_info` parameter is the generic representation that needs to be filled in by the platform. This parameter is initialised to `0` or `PSCI_LOCAL_STATE_RUN`. This means that to begin with, all power domains are in the RUN state. The platform should interpret the `power_state` parameter to decide whether a power domain should enter a STANDBY/OFF state or continue to be in the RUN state. This is subject to ordering rules i.e. a power domain at level X cannot be in a shallower state that the power domain at level X+1.

>
> I have the following code in my _validate_power_state() handler for Tegra.
>
>
> /*******************************************************************************
>
>   * Platform power states
>     ******************************************************************************/
>     #define PLAT_MAX_RET_STATE 1 #define PLAT_MAX_SUSPEND_STATE 2 #define
>     PLAT_MAX_OFF_STATE 3
>
> int32_t tegra_soc_validate_power_state(unsigned int power_state,
> psci_power_state_t *req_state)
> {
> int pwr_lvl = psci_get_pstate_pwrlvl(power_state);
> int state_id = psci_get_pstate_id(power_state);
>
> |/* Sanity check the requested afflvl */
> if (psci_get_pstate_type(power_state) == PSTATE_TYPE_STANDBY) {
>      /*
>       * It's possible to enter standby only on affinity level 0 i.e.
>       * a cpu on Tegra. Ignore any other affinity level.
>       */
>      if (pwr_lvl != MPIDR_AFFLVL0)
>          return PSCI_E_INVALID_PARAMS;
>
>      /* power domain in standby state */
>      req_state->pwr_domain_state[pwr_lvl] = PLAT_MAX_RET_STATE;
> }
>
> /* Sanity check the requested state id */
> if (state_id != PLAT_SYS_SUSPEND_STATE_ID) {
>      ERROR("unsupported state id\n");
>      return PSCI_E_NOT_SUPPORTED;
> }
>
> /* Get the suspend state-id */
> suspend_id = state_id;
> flush_dcache_range((uint64_t)&suspend_id, sizeof(suspend_id));
>
> /* power domain in suspend state */
> req_state->pwr_domain_state[MPIDR_AFFLVL0] = PLAT_MAX_SUSPEND_STATE;
>
> return PSCI_E_SUCCESS;
> |
>
> }
>
> If I remove the lines to set "req_state->pwr_domain_state", then the asserts are
> seen.

If you remove these lines and the requested `power_state` is a power down state, then the generic representation `req_state` of the power state will indicate that all power levels should remain in a RUN state (`0`). When `psci_validate_suspend_req()` is called, `psci_find_target_suspend_lvl()` will return `PSCI_INVALID_PWR_LVL` since not even a single power domain has been requested to enter a low power state. This will cause the assertion you mentioned to fire.

hth,
Achin
>
> Will try the compat code and let you know if I see any issues.
>
> Thanks.
>
> �
> Reply to this email directly or view it on GitHub
> <https://github.com/ARM-software/arm-trusted-firmware/pull/346#issuecomment-128593320>.
>

-- IMPORTANT NOTICE: The contents of this email and any attachments are confidential and may also be privileged. If you are not the intended recipient, please notify the sender immediately and do not disclose the contents to any other person, use it for any purpose, or store or copy the information in any medium.  Thank you.

ARM Limited, Registered office 110 Fulbourn Road, Cambridge CB1 9NJ, Registered in England & Wales, Company No:  2557590
ARM Holdings plc, Registered office 110 Fulbourn Road, Cambridge CB1 9NJ, Registered in England & Wales, Company No:  2548782

**Comment by vwadekar** [comment]
Great.  Glad to know that the Tegra port is correct.

**Comment by achingupta** [comment]
Hi Varun,

On 07/08/15 11:25, varunw-nvidia wrote:> Great. Glad to know that the Tegra port is correct.

It does the trick at the moment but there are few things to keep in mind. Please see inline.

>
> On Fri, Aug 7, 2015, 3:49 PM Achin Gupta <notifications@github.com> wrote:
>
>> Hi `,
>>
>> On 07/08/15 05:26, varunw-nvidia wrote:> @achingupta <
>> https://github.com/achingupta>

[snip]

>> > I have the following code in my _validate_power_state() handler for
>> Tegra.
>> >
>> >
>> >
>> /*******************************************************************************
>> >
>> > * Platform power states
>> >
>> ******************************************************************************/
>> > #define PLAT_MAX_RET_STATE 1 #define PLAT_MAX_SUSPEND_STATE 2 #define
>> > PLAT_MAX_OFF_STATE 3
>> >
>> > int32_t tegra_soc_validate_power_state(unsigned int power_state,
>> > psci_power_state_t *req_state)
>> > {
>> > int pwr_lvl = psci_get_pstate_pwrlvl(power_state);
>> > int state_id = psci_get_pstate_id(power_state);
>> >
>> > |/* Sanity check the requested afflvl */
>> > if (psci_get_pstate_type(power_state) == PSTATE_TYPE_STANDBY) {
>> > /*
>> > * It's possible to enter standby only on affinity level 0 i.e.
>> > * a cpu on Tegra. Ignore any other affinity level.
>> > */
>> > if (pwr_lvl != MPIDR_AFFLVL0)
>> > return PSCI_E_INVALID_PARAMS;
>> >
>> > /* power domain in standby state */
>> > req_state->pwr_domain_state[pwr_lvl] = PLAT_MAX_RET_STATE;
>> > }
>> >
>> > /* Sanity check the requested state id */
>> > if (state_id != PLAT_SYS_SUSPEND_STATE_ID) {
>> > ERROR("unsupported state id\n");
>> > return PSCI_E_NOT_SUPPORTED;

PSCI CPU_SUSPEND cannot return `PSCI_E_NOT_SUPPORTED`. This could lead to an assertion failure in `psci_cpu_suspend()`.

>> > }
>> >
>> > /* Get the suspend state-id */
>> > suspend_id = state_id;
>> > flush_dcache_range((uint64_t)&suspend_id, sizeof(suspend_id));
>> >
>> > /* power domain in suspend state */
>> > req_state->pwr_domain_state[MPIDR_AFFLVL0] = PLAT_MAX_SUSPEND_STATE;

I have not seen the Tegra port you have shared but if the implementation of this function is the same then all power down requests will result only in a core shutdown. You are ignoring the target power level in the `power_state` parameter. The requested state of each power domain until the target power level should be set. Have a look at `arm_validate_power_state` in `plat/arm/common/arm_pm.c`

hth,
Achin

>> Reply to this email directly or view it on GitHub
>> <https://github.com/ARM-software/arm-trusted-firmware/pull/346#issuecomment-128666437>
>> .
>>
>
> �
> Reply to this email directly or view it on GitHub
> <https://github.com/ARM-software/arm-trusted-firmware/pull/346#issuecomment-128667735>.
>

-- IMPORTANT NOTICE: The contents of this email and any attachments are confidential and may also be privileged. If you are not the intended recipient, please notify the sender immediately and do not disclose the contents to any other person, use it for any purpose, or store or copy the information in any medium.  Thank you.

ARM Limited, Registered office 110 Fulbourn Road, Cambridge CB1 9NJ, Registered in England & Wales, Company No:  2557590
ARM Holdings plc, Registered office 110 Fulbourn Road, Cambridge CB1 9NJ, Registered in England & Wales, Company No:  2548782

**Comment by achingupta** [comment]
Hi Varun,

On 07/08/15 07:03, varunw-nvidia wrote:> I verified the Tegra port with the compatibility layer and all things work fine.
> I have updated one change that I had to do in plat_pm_compat.c. Else the
> platform worked (basic boot, secondary CPU ON/OFF, cpu suspend, system suspend)
> out of the box. Thanks.

Copying your inline comment here:

>> I had to add a flush_dcache_range() to get CPU_SUSPEND working on Tegra. FWIW, we set USE_COHERENT_MEM=0 for T210/T132 platforms. Is cache flush required when USE_COHERENT_MEM=0?

There might be a bug here! Are you facing an issue with SYSTEM_SUSPEND since the comment was left in `get_sys_suspend_power_state_compat()` function. IIUC, you should see the problem only when a core (not the cluster) is suspended. This is 'cause:

1.  The compatibility layer does not perform cache maintenace when the `psci_power_state_compat` array is updated in `plat_pm_compat.c`.
2.  `tegra_affinst_suspend()` calls `psci_get_suspend_stateid()` which in turn accesses `psci_power_state_compat`. This is done with the D$ disabled as their maintenance has already been done. If only the core is being powered down only the L1 cache will be flushed. Its contents are more likely to reside in L2 rather than main memory. However, since the D$ is disabled the core will access main memory. This is where a flush by MVA will help. In fact in the implementation of `psci_set_suspend_power_state()` earlier, there was a similar flush to ensure that the data has made its way to main memory.

Does the above make sense to you?

Thanks,
Achin

>
> �
> Reply to this email directly or view it on GitHub
> <https://github.com/ARM-software/arm-trusted-firmware/pull/346#issuecomment-128607670>.
>

-- IMPORTANT NOTICE: The contents of this email and any attachments are confidential and may also be privileged. If you are not the intended recipient, please notify the sender immediately and do not disclose the contents to any other person, use it for any purpose, or store or copy the information in any medium.  Thank you.

ARM Limited, Registered office 110 Fulbourn Road, Cambridge CB1 9NJ, Registered in England & Wales, Company No:  2557590
ARM Holdings plc, Registered office 110 Fulbourn Road, Cambridge CB1 9NJ, Registered in England & Wales, Company No:  2548782

**Comment by soby-mathew** [comment]
retest this please

**Comment by vwadekar** [comment]
>> There might be a bug here! Are you facing an issue with SYSTEM_SUSPEND since the comment was left in `get_sys_suspend_power_state_compat()` function

Yes, I see this problem when a core is trying to enter suspend.

**Comment by vwadekar** [comment]
> Have a look at `arm_validate_power_state` in `plat/arm/common/arm_pm.c`

In the latest patch I have fixed this by using the logic from this file.

**Comment by soby-mathew** [comment]
Superseded by new PR - https://github.com/ARM-software/arm-trusted-firmware/pull/354

**Comment by soby-mathew** [comment]
Superseded by new PR - #355

**Pull request closed without merging**
