### PR TITLE
TLK dispatcher

### PR DESCRIPTION
**Pull request by vwadekar**
This topic branch adds the TLK dispatcher to the mix. This dispatcher helps TLK to run with the Trusted Firmware.

Verification: Code compiles with the master branch.

v1: fixes comments from tlkd branch.
v2: fixes comments from tlkd-fixed-v1 branch.
v3: fixes Dan's comments from tlkd-fixed-v2 branch.

### CODE REVIEW

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by vwadekar** [comment]
Dan/Achin, any other comments for the PR? Is it good to go?

**Comment by danh-arm** [comment]
It's done, Varun. Thanks.

**Comment by vwadekar** [comment]
Thanks a lot, Dan. What's the typical time required for a change to get to the master branch from the integration branch?

**Comment by danh-arm** [comment]
Hi Varun. It should be a day or two, although the master branch has been lagging behind integration for about 12 days now. I'll make sure this is caught up within the next day. Regards, Dan.

**Comment by vwadekar** [comment]
Thanks Dan. I have the shared memory cleaned up from the dispatcher. I'm waiting for the master branch to be in sync with integration to push this commit.

**Pull request merged**
