### PR TITLE
Fix normal memory bakery lock implementation

### PR DESCRIPTION
**Pull request by soby-mathew**
This patch fixes an issue in the normal memory bakery lock
implementation. During assertion of lock status, there is a possibility
that the assertion could fail. This is because the previous update done
to the lock status by the owning CPU when not participating in cache
coherency could result in stale data in the cache due to cache maintenance
operations not propagating to all the caches. This patch fixes this issue
by doing an extra read cache maintenance operation prior to the assertion.

Fixes ARM-software/tf-issues#402

Change-Id: I0f38a7c52476a4f58e17ebe0141d256d198be88d
Signed-off-by: Soby Mathew <soby.mathew@arm.com>

### CODE REVIEW

**Comment by danh-arm** [comment]
Hi @vwadekar

Soby went ahead and implemented his proposed fix to ARM-software/tf-issues#402. This will supersede your #656 PR. Let us know if you have any issues otherwise I will merge.

Regards

Dan.

**Comment by davidcunado-arm** [comment]
Hi @vwadekar,

I'm planning on merging this tomorrow, WED 30-NOV - please let me know before then whether you have any issues?

Thanks,

David

**Comment by vwadekar** [comment]
Hi David,

I won't be able to test this patch until Wed. But the implementation looks
similar to the one we have downstream.

One question - don't we want the code to run as part of release builds too
- as asserts won't be compiled there?

**Comment by soby-mathew** [comment]
> One question - don't we want the code to run as part of release builds too - as asserts won't be compiled there?

The read in the assert() was accessing stale data on the cache line. Hence the need for cache maintenance ops prior to read. 
The idea is to keep the bakery lock info coherent with the memory just enough to ensure correctness of the algorithm, but not `always coherent` as it would be too expensive. Hence in release mode, the asserts are not present and the associated read cache operations need not be present too.

**Comment by vwadekar** [comment]
Thanks Soby. That answers my question.

**Comment by davidcunado-arm** [comment]
Hi @vwadekar 
I've closed your PR #656 as this PR resolves the issue and has now been merged.
Thanks,
David

**Pull request merged**
