### PR TITLE
plat/arm/sgi: Use NT_FW_CONFIG instead of HW_CONFIG

### PR DESCRIPTION
**Pull request by chandnich**
With the two new APIs 'plat_arm_sgi_get_platform_id' and
'plat_arm_sgi_get_config_id' that are available now, BL31 need not
depend on hw_config device tree to identify the platform. In addition
to this, the existing hardware description in hw_config can be limited
to use by BL33 and not by the operating system.

So the hardware description from hw_config dts can be moved into
nt_fw_config dts and the use of hw_config dts can be removed.

Change-Id: I873b7e1e72823d3ec5d253a848e85ae724f09e49
Signed-off-by: Chandni Cherukuri <chandni.cherukuri@arm.com>

### CODE REVIEW

**Comment by omasab** [comment]
jenkins: test this please

**Comment by soby-mathew** [comment]
jenkins: add to whitelist

**Comment by soby-mathew** [comment]
@npoushin has confirmed that the patches are OK.

**Comment by chandnich** [comment]
https://lists.01.org/pipermail/edk2-devel/2018-December/033484.html has been merged in edk2-platforms

**Pull request merged**
