### PR TITLE
qemu: Fix interrupt type check

### PR DESCRIPTION
**Pull request by ssalko**
Function plat_ic_get_pending_interrupt_type() should return interrupt
type, not id. The function is used in aarch64 exception handling and
currently the irq/fiq forwarding fails if a secure interrupt happens while
running normal world.

The qemu-specific gic file does not contain any extra functionality so it
can be removed and common file can be used instead.

fixes arm-software/tf-issues#546

Signed-off-by: Santeri Salko <santeri.salko@gmail.com>

### CODE REVIEW

**Comment by davidcunado-arm** [comment]
@ssalko 
As per the contributing guidelines, please target the integration branch instead of the master branch in future. I've updated this PR.

**Comment by davidcunado-arm** [comment]
jenkins: test this please

**Comment by davidcunado-arm** [comment]
@jenswi-linaro 
Please ACK change to QEMU support?

**Comment by davidcunado-arm** [comment]
check failures - static analysis issues in existing code (gicv2 support); ignore.

**Comment by davidcunado-arm** [comment]
jenkins: test this please

**Comment by davidcunado-arm** [comment]
@jenswi-linaro 
I'll look to merge this at the end of the week - please let me know if you have any concerns. Thanks!

**Comment by jenswi-linaro** [comment]
Sorry, missed this. Nice cleanup. I'll try to update my mail filters to notice these updates.

**Pull request merged**
