### PR TITLE
Fix several MISRA defects in PSCI library

### PR DESCRIPTION
**Pull request by antonio-nino-diaz-arm**

### CODE REVIEW

**Comment by antonio-nino-diaz-arm** [comment]
The only commit that touches platform code is "Fix several MISRA defects in PSCI library".

**Comment by b49020** [comment]
For plat/socionext/synquacer/, `Acked-by: Sumit Garg <sumit.garg@linaro.org>`

**Comment by jenswi-linaro** [comment]
OK for plat/qemu part

**Comment by shawnguo2** [comment]
ACK on plat/hisilicon/poplar/include/platform_def.h

**Comment by Anson-Huang** [comment]
For plat/imx part, Acked-by: Anson Huang <Anson.Huang@nxp.com>

Anson Huang
Best Regards!
[cid:image002.png@01D39624.69C9AC90]

**Comment by TonyXie06** [comment]
OK for plat/rockchip part

**Pull request merged**
