### PR TITLE
qemu: Support SEPARATE_CODE_AND_RODATA

### PR DESCRIPTION
**Pull request by michpappas**
Update qemu_configure_mmu_##_el to add an additional region for code,
marked as MT_CODE | MT_SECURE. Update ro region attributes to NON_EXEC.

Update calls to QEMU_CONFIGURE_BLx_MMU() to pass an additional region for
code. Update calls to pass regions defined in common_def.h.

Increase MAX_MMAP_REGIONS to 10.

Enable SEPARATE_CODE_AND_RODATA by default on QEMU builds.

Fixes ARM-software/tf-issues#558

Signed-off-by: Michalis Pappas <mpappas@fastmail.fm>

### CODE REVIEW

**Comment by antonio-nino-diaz-arm** [comment]
Instead of having that merge commit, could you rebase the patch?

**Comment by michpappas** [comment]
@antonio-nino-diaz-arm apologies, I used github's web interface to resolve the conflict. Hope it's okay now :)

**Comment by antonio-nino-diaz-arm** [comment]
Yes, now it's fine. The web interface isn't exactly great...

**Comment by davidcunado-arm** [comment]
@jenswi-linaro 
Please ACK?

**Comment by jenswi-linaro** [comment]
Looks good to me

**Comment by davidcunado-arm** [comment]
Checks - passed

**Pull request merged**
