### PR TITLE
hikey960: add asp dma non-secure mode setting

### PR DESCRIPTION
**Pull request by xu-yiping**
init asp dma to non-secure mode.

Signed-off-by: Youlin Wang <wangyoulin1@hisilicon.com>
Signed-off-by: Tanglei Han <hantanglei@huawei.com>
Signed-off-by: Xu YiPing <xuyiping@hisilicon.com>

### CODE REVIEW

**Comment by xu-yiping** [comment]
@hzhuang1 , please review, thanks

**Comment by johnstultz-work** [comment]
@oscardagrach Can you review this to see how this is different from the patch you submitted earlier:
https://github.com/ARM-software/arm-trusted-firmware/pull/1703/files

Want to make sure nothing was missed.

**Comment by oscardagrach** [comment]
@johnstultz-work This initializes the ASP DMA (DMA-a) controller as opposed to the peripheral DMA controller (DMA-p) my patch enabled. A similar patch will be required for the IOMCU DMA controller in the future. It is my anecdotal understanding the DMA-a controller does not require this initialization as it is accessible in non-secure mode by default.

**Comment by johnstultz-work** [comment]
@oscardagrach Ah! Thanks for the clarification!  I too haven't observed the need for this DMA-A initialization yet, but doing it explicitly is probably better then assuming. It may have effects on other platforms that share the IP.

I'll follow up with @xu-yiping to see why this got closed.

**Pull request closed without merging**
