### PR TITLE
MT8173: Add Sip function for MTK HW crypt driver

### PR DESCRIPTION
**Pull request by mtk09422**
previous review https://github.com/ARM-software/arm-trusted-firmware/pull/616

### CODE REVIEW

**Comment by danh-arm** [comment]
jenkins:test this please

**Comment by danh-arm** [comment]
This PR looks OK to me but please rebase on latest master to resolve conflicts. You may force push to the existing branch rather than create a new PR (as per the new guidelines).

**Comment by mtk09422** [comment]
the conflict is resolved in v3 patch.

**Comment by danh-arm** [comment]
Superseded by #622

**Pull request closed without merging**
