### PR TITLE
Console: Use callee-saved registers

### PR DESCRIPTION
**Pull request by satheesbalya-arm**
Change-Id: Ibac859c4bcef0e92a0dcacc6b58ac19bc69b8342
Signed-off-by: Sathees Balya <sathees.balya@arm.com>

### CODE REVIEW

**Comment by jeenu-arm** [comment]
jenkins: add to whitelist

**Comment by jeenu-arm** [comment]
jenkins: test this please

**Comment by dp-arm** [comment]
jenkins: test this please

**Comment by dp-arm** [comment]
jenkins: test this please

**Pull request merged**
