### PR TITLE
RK3399 GIC save/restore

### PR DESCRIPTION
**Pull request by dbasehore**
This fixes several things in generic GICv3 code and RK3399 specific code. It then enables save/restore for the GICv3 on RK3399.

### CODE REVIEW

**Comment by computersforpeace** [comment]
(Not familiar with github reviews...I thought I was reviewing a commit at a time. Oh well. So far, I've only reviewed the first 4 commits.)

Also @jwerner-chromium FYI. I thought we've complained about the tight loops before (e.g., in the 4th commit), so udelay()s would be welcome I think.

**Comment by dbasehore** [comment]
Is an approval from Rockchip needed for these patches?

**Comment by dbasehore** [comment]
Okay, it seems that another patch is needed for this to work with upstream Linux. I'll post soon, so please don't pull before that.

**Comment by dbasehore** [comment]
Okay, I'd like to get Rockchip to approve the latest patch I added. I'm pretty sure it's fine, but it's in their common code.

**Comment by Caesar-github** [comment]
Okay,  look good to me. I will fetch them for rockchip inside ATF. 

~Thanks.

-Caesar

**Comment by davidcunado-arm** [comment]
@Caesar-github @TonyXie06 
Please confirm that this PR is acceptable?

**Comment by computersforpeace** [comment]
Is that not what Caesar did above?

**Comment by Caesar-github** [comment]
@davidcunado-arm  
Yes. it's.
David, please help merge it, thanks!

**Comment by davidcunado-arm** [comment]
jenkins: test this please

**Comment by davidcunado-arm** [comment]
Check fail - looks like there was a temp infrastructure issue that caused one test to fail; on re-running that failing test, it passed.
Ok to merge.

**Pull request merged**
