### PR TITLE
Enable asynchronous abort exceptions

### PR DESCRIPTION
**Pull request by ljerry**
On r0p2 revision and above revision, despite what is stated in ARM DDI0500D TRM
Cortex A53 r0p2 SCR_EL3 description in Table 4-77, asynchronous exceptions
generated by the code running in EL3 are not taken in EL3 when SCR_EL3[EA] is
zero.
DDI0487A.b Architecture Reference Manual does not reflect the actual
behaviour of r0p2.

DDI0487A.e Architecture Reference Manual D7.2.80 SCR_EL3 description depicts
the observed behaviour.

Fixes arm-software/tf-issues#368

Signed-off-by: Gerald Lejeune <gerald.lejeune@st.com>

### CODE REVIEW

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by danh-arm** [comment]
Firstly, the commit message for this needs complete rework. It reads like a bug report on the ARM ARM document, which has now been fixed anyway. Instead you should describe how you're enabling the EA bit during cold boot to improve detection of EAs generated by EL3 code, and optionally allowing the EA bit to remain set at runtime (default behaviour is to set back to zero). If you like, you could mention that in A53 revisions prior to r0p2, SError interrupts generated while executing in EL3 are taken in EL3, even when the EA bit is clear. But that is really just background information.

**Comment by danh-arm** [comment]
You need to remove https://github.com/ARM-software/arm-trusted-firmware/pull/548/commits/af8c99a162ffefeb27b4cd4d285eab021151f7a9 from this PR as that is an independent change.

**Comment by ljerry** [comment]
Sorry I missed your previous comment. I'll clean commit message up in a while.

**Comment by danh-arm** [comment]
Superseded by #554

**Pull request closed without merging**
