### PR TITLE
Allow to override toolchain

### PR DESCRIPTION
**Pull request by paulmenzel**

### CODE REVIEW

**Comment by dp-arm** [comment]
You can still do make CC=clang and it will work.  I agree however that CC=clang make should also work.

**Comment by paulmenzel** [comment]
Indeed, the user guide says `export CC=…` though.

**Comment by davidcunado-arm** [comment]
jenkins: test this please

**Comment by davidcunado-arm** [comment]
jenkins: retest this please

**Comment by dp-arm** [comment]
> Indeed, the user guide says export CC=… though.

The guide mentions export CROSS_COMPILE though unless I am totally missing something.

**Comment by davidcunado-arm** [comment]
@paulmenzel 
Unfortunately, we're not going to be able to accept this change in its current state. 

The build scripts have been written with this restrictiveness, which is relied upon by our CI environment. 

With this change the checks failures because the build machine environments have CC defined by default to the native compiler and so all the CI builds fail.

**Comment by davidcunado-arm** [comment]
@paulmenzel 
Closing as per earlier comment.

**Pull request closed without merging**
