### PR TITLE
Tegra: introduce per-soc system reset handler

### PR DESCRIPTION
**Pull request by vwadekar**
This patch adds a per-soc system reset handler for Tegra chips. The
handler gets executed before the actual system resets. This allows
for custom handling of the system reset sequence on each SoC.

Signed-off-by: Varun Wadekar <vwadekar@nvidia.com>

### CODE REVIEW

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by achingupta** [comment]
test this please

**Comment by vwadekar** [comment]
@achingupta 

Hello,

I wanted to update this PR a bit. Since there were no review comments, I think that should fine. Please correct me if that's incorrect.

**Comment by vwadekar** [comment]
New PR - #428

**Pull request closed without merging**
