### PR TITLE
 RK3399: Shrink M0 SRAM code to fit in PMUSRAM

### PR DESCRIPTION
**Pull request by rkchrome**
To turn off the Logic voltage rail during S3, we need to move M0 text and data from SRAM to PMUSRAM. The M0 code and data are still too large, though. This bug is for tracking progress on shrinking and moving the M0 text and data sections.

### CODE REVIEW

**Comment by danh-arm** [comment]
jenkins: test this please

**Comment by danh-arm** [comment]
This PR fails to build the RK3228 platform:
```
CROSS_COMPILE=aarch64-linux-gnu- V=1 DEBUG=1 PLAT=rk3328
...
make: *** No rule to make target `plat/rockchip/common/pmusram/pmu_sram.c', needed by `build/rk3328/debug/bl31/pmu_sram.o'.  Stop.
```
It looks like you've removed a file that this platform still needs.

**Comment by rkchrome** [comment]
Sorry, looks like the rk3328 had been supported on upstream ATF.
Update the patch to solve the build error for rk3328, and Tony will support the rk3328 in later.

**Comment by danh-arm** [comment]
jenkins:retest this please

**Pull request merged**
