### PR TITLE
meson: gxl: Fix reset and power off

### PR DESCRIPTION
**Pull request by repk**
Before CPU enters standby state (wfi), the AP needs to signal the SCP
through PSCI mailbox.

Also at boot time the AP has to wait for the SCP to be ready before
sending the first scpi commands or it can crash.

### CODE REVIEW

**Comment by antonio-nino-diaz-arm** [comment]
As part of the migration to trustedfirmware.org https://github.com/ARM-software/tf-issues/issues/681 we have switched the main development repository to Gerrit (https://review.trustedfirmware.org/). It is unfortunate that the switch has happened while your PR was being reviewed, but we don't intend to merge more patches through GitHub to avoid confusion.

Could you please follow the instructions in https://github.com/ARM-software/arm-trusted-firmware/blob/master/contributing.rst to continue with the review? We're sorry for the inconvenience.

**Comment by sandrine-bailleux-arm** [comment]
In addition to the [contribution guidelines](https://github.com/ARM-software/arm-trusted-firmware/blob/master/contributing.rst), the following [Getting starting guide](https://developer.trustedfirmware.org/w/tf_a/gerrit-getting-started/) might help in this process.

**Comment by antonio-nino-diaz-arm** [comment]
This patch fixes the reboot issue, but CPU hotplug doesn't really work well:
```
root@libre-computer:/home/libre# echo 0 > /sys/devices/system/cpu/cpu1/online
[   57.963410] CPU1: shutdown
[   57.963505] psci: CPU1 killed.
root@libre-computer:/home/libre# echo 0 > /sys/devices/system/cpu/cpu2/online
[   62.863409] CPU2: shutdown
[   62.883207] psci: Retrying again to check for CPU kill
[   62.903204] psci: Retrying again to check for CPU kill
[   62.923203] psci: Retrying again to check for CPU kill
[   62.943204] psci: Retrying again to check for CPU kill
[   62.963204] psci: Retrying again to check for CPU kill
[   62.983203] psci: Retrying again to check for CPU kill
[   63.003202] psci: Retrying again to check for CPU kill
[   63.023205] psci: Retrying again to check for CPU kill
[   63.043202] psci: Retrying again to check for CPU kill
[   63.063203] psci: Retrying again to check for CPU kill
[   63.063367] psci: CPU2 may not have shut down cleanly (AFFINITY_INFO reports 0)
[   63.071052] CPU2 may not have shut down cleanly: -110
root@libre-computer:/home/libre# echo 1 > /sys/devices/system/cpu/cpu2/online
[   74.768128] psci: failed to boot CPU2 (-22)
[   74.768272] CPU2: failed to boot: -22
[   74.770378] CPU2: failed in unknown state : 0x0
```
It tends to happen with other CPUs as well.

**Comment by repk** [comment]
Yes I saw problems with CPU hotplug also, not exactly the same thing as yours though. But I thought It was a different problem from the system reset one. I'll, maybe, try to fix that in the same patchset.

Anyway I'm closing this PR and go through the gerrit process.

**Pull request closed without merging**
