### PR TITLE
Retention entry v3

### PR DESCRIPTION
**Pull request by vwadekar**

### CODE REVIEW

**Comment by vwadekar** [comment]
Previous PR - #370

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by vwadekar** [comment]
@danh-arm @achingupta 

Hello Dan/Achin,

Please let me know if there are any more changes required for this PR.

Thanks

**Comment by achingupta** [comment]
retest this please

**Comment by achingupta** [comment]
retest this please

**Comment by vwadekar** [comment]
Thanks Achin.

**Pull request merged**
