### PR TITLE
Support for NVIDIA's Tegra T210 SoCs

### PR DESCRIPTION
**Pull request by vwadekar**
T210 is the latest chip in the Tegra family of SoCs from NVIDIA. It is an
ARM v8 dual-cluster (A57/A53) SoC, with any one of the clusters being active
at a given point in time.

This patch adds support to boot the Trusted Firmware on T210 SoCs. The patch
also adds support to boot secondary CPUs, enter/exit core power states for
all CPUs in the slow/fast clusters. The support to switch between clusters
is still not available in this patch and would be available later.

Signed-off-by: Varun Wadekar <vwadekar@nvidia.com>

### CODE REVIEW

**Comment by vwadekar** [comment]
Hello Dan, please let me know if there's some more documentation needed.

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by vwadekar** [comment]
Hello Dan. I have obviously messed up the copyrights, but will wait for
your feedback for the code as well before pushing another patch. Thanks.

**Comment by vwadekar** [comment]
https://github.com/ARM-software/arm-trusted-firmware/pull/302 is the new PR with some minor code comment and copyright fixes.

**Pull request closed without merging**
