### PR TITLE
Minor docs

### PR DESCRIPTION
**Pull request by etienne-lms**
2 minor fixes related to documentation.

### CODE REVIEW

**Comment by davidcunado-arm** [comment]
@etienne-lms 
This PR needs re-basing as the documentation has migrated to .rst format files.
Thanks!

**Comment by davidcunado-arm** [comment]
@etienne-lms 
Any update on this PR?

**Comment by etienne-lms** [comment]
Sorry. I must rebase it. I will do that by today.

**Comment by etienne-lms** [comment]
rebased

**Comment by davidcunado-arm** [comment]
jenkins: test this please

**Pull request merged**
