### PR TITLE
Tegra soc support v3

### PR DESCRIPTION
**Pull request by vwadekar**
T210 is the latest chip in the Tegra family of SoCs from NVIDIA. It is an
ARM v8 dual-cluster (A57/A53) SoC, with any one of the clusters being active
at a given point in time.

This PR adds support to boot the Trusted Firmware on T210 SoCs. The patch
also adds support to boot secondary CPUs, enter/exit core power states for
all CPUs in the slow/fast clusters. The support to switch between clusters
is still not available in this patch and would be available later.

### CODE REVIEW

**Comment by vwadekar** [comment]
Fixed comments from #304

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by achingupta** [comment]
test this please

**Comment by vwadekar** [comment]
New pull request - #308

**Pull request closed without merging**
