### PR TITLE
Correct preprocessor conditionals

### PR DESCRIPTION
**Pull request by masahir0y**

### CODE REVIEW

**Comment by danh-arm** [comment]
jenkins: test this please

**Comment by davidcunado-arm** [comment]
jenkins: retest this please

**Comment by davidcunado-arm** [comment]
Hi @masahir0y 
I've created arm-trusted-firmware/pull/811 to resolve the check failure in your patch. Once it's merged it may require a rebase / merge as my change looks to be quite close to yours in that particular file.
Thanks!

**Comment by davidcunado-arm** [comment]
jenkins: test this please.

**Comment by davidcunado-arm** [comment]
jenkins: test this please

**Comment by masahir0y** [comment]
I did not touch this pull-request because jenkins was testing it.

If any action is needed on my side, please let me know.

**Comment by danh-arm** [comment]
Hi @masahir0y. Sorry, there was an integration problem our side. Could you please rebase again and we will retest/merge this.

**Comment by masahir0y** [comment]
Now, rebased on the current master.

**Comment by davidcunado-arm** [comment]
jenkins: test this please

**Pull request merged**
