### PR TITLE
GICv3 context save and restore

### PR DESCRIPTION
**Pull request by douglas-raillard-arm**
Introduce helpers to save and restore the context of GICv3:
* Distributor
* Redistributor
* For Distributor and Redistributor, the helpers also support the implementation-defined part of GIC-500 and GIC-600
* ITS (only the architectural part, most of the work needs to be done according to the ITS implementation of the platform)

### CODE REVIEW

**Comment by dbasehore** [comment]
Is there any progress on getting these patches merged into master?

**Comment by soby-mathew** [comment]
There were some minor updates to this PR .  This is now superceded by PR #1116 .

**Comment by soby-mathew** [comment]
There is an ongoing discussion regarding ITS save and restore sequence. Depending on the outcome of that discussion, the ITS helpers in firmware may be removed. Also the ITS restore helper currently restores the GITS_CTLR which may not be correct.  The firmware needs to disable the ITS on restore and leave the ITS enable to kernel.

Hope to have this resolved tomorrow.

**Comment by davidcunado-arm** [comment]
Closing as has been superceded by PR #1116

**Pull request closed without merging**
