### PR TITLE
Remove deprecated interfaces

### PR DESCRIPTION
**Pull request by ambroise-arm**
Remove some of the deprecated interfaces listed in the "TF-A Release Information" document.

### CODE REVIEW

**Comment by antonio-nino-diaz-arm** [comment]
jenkins: test this please

**Comment by antonio-nino-diaz-arm** [comment]
jenkins: test this please

**Comment by antonio-nino-diaz-arm** [comment]
jenkins: test this please

**Comment by antonio-nino-diaz-arm** [comment]
The CI failure is due to a static checks script that has crashed, everything else is fine.

**Comment by jenswi-linaro** [comment]
OK for plat/qemu

**Pull request merged**
