### PR TITLE
Tegra supports psci1.0 v3

### PR DESCRIPTION
**Pull request by vwadekar**
Tegra: support PSCI v1.0 framework implementation

This patch modifies the Tegra port to support the new PSCI v1.0
implementation. This includes modifications to the power management
and platform topology code.

Previous PR - #372, #378

### CODE REVIEW

**Comment by vwadekar** [comment]
@soby-mathew 

Hello Soby,

Let me know if this is OK.

Thanks.

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by danh-arm** [comment]
Can one of the admins verify this patch?

**Comment by vwadekar** [comment]
@danh-arm @achingupta 

Hello Dan/Achin,

Would you be able to take a look today?

Thanks.

**Comment by danh-arm** [comment]
Varun - we're perfectly aware that this PR is outstanding, we do not need to be reminded. If there is a valid requirement for this to be integrated by a certain date, then please state the date and reasoning here. If your development process is sensitive to delays of a few days in integration then something is probably broken with your process. Simply asking us to "take a look today" is not a good enough reason for us to prioritise this and will not make it go any faster.

**Comment by vwadekar** [comment]
@danh-arm 

Dan, I am not sure what makes you think that not responding for days and then blasting out all of a sudden is warranted. I know that I have been polite and would request you to be cordial too! Do you expect me to be a psychic and understand why there's no review?

Soby has already reviewed it and Achin/Soby mentioned that this PR would be reviewed early this week. Is there a problem if we inquire about the status? If yes, then please set up a proper process which works for all of us. I would be happy to give my inputs.

The development process works with all components from upstream and hence the request. There are some more changes pending on top of this change and to avoid any unwanted churn (using previous code now and then moving later) we were hoping if we can get this PR reviewed.

**Comment by vwadekar** [comment]
NEw PR - #440

**Pull request closed without merging**
